### ISSUE TITLE
[RFC] Componentizing Links with wRPC

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1389]
### RFC Title

RFC: Componentizing Links with wRPC

### Introduction

*wRPC stands for wRPC Remote Procedure Calls*

Goal: Provide distributed component support via wasmCloud

Since the [unveiling of wasmCloud](https://kevinhoffman.medium.com/introducing-waxosuit-6ad754b48ed9) our RPC framework enabled server-side WebAssembly applications. The core of this framework is the idea that we send invocations over a distributed network, NATS, based on capability contracts that form the building blocks of applications. These capability contracts included things like HTTP servers in `wasmcloud:httpserver`, key-value stores in `wasmcloud:keyvalue`, pubsub messaging in `wasmcloud:messaging`, logging in `wasmcloud:builtin:logging`, etc. The business logic components that wish to use the abstract capability and the actual implementation are completely separate entities at compile time, and can communicate using link definitions that connect them at runtime.

With the WebAssembly component model, defining our interfaces in WIT, and the stabilization of WASI 0.2.0, everything changes with the way we handle RPC.

### Motivation

[wasmCloud aims to support as many Wasm standards as possible](https://wasmcloud.com/docs/roadmap/q3q4#goals) to enable the goals of the project. We currently support the Wasm component model by using the concept of polyfills, essentially translating the wasmCloud contracts into standard WASI interfaces and vice versa. For example, when you load a component that exports the `wasi:http/incoming-handler` function, this is what happens:

![Untitled](https://github.com/wasmCloud/wasmCloud/assets/12040685/426cc784-a595-4cb2-8c19-f41e41e5dd76)

We don’t want to keep up this mapping forever. Polyfilling wasmCloud contracts that were built in a time where standard interfaces did not exist doesn’t make sense to do when there are standard interfaces that exist. In this case, the ideal mapping would be something like:
![Untitled2](https://github.com/wasmCloud/wasmCloud/assets/12040685/e9a54be2-7f76-4417-b887-7066dacd62a6)

In this case, the implementation of the WASI interface (which could be a capability provider, a simple HTTP listener, or a test module) can directly call that exported function on the actor component. Note above that we are still going through wasmCloud as a sort of middleman, and that’s because we still want the host to be responsible for dealing with the complexity of a distributed use case. In their design, Wasm components are explicitly designed to be composed together where one Wasm component’s imports can satisfy the others exports and vice versa.

**************************************************We want wasmCloud RPC to feel like composing components, at runtime, over the lattice.**************************************************

### Detailed Design

Core to this design is the [wRPC protocol proposal](https://github.com/rvolosatovs/wrpc/blob/main/design.md) which focuses on the structure of the RPC topics that Wasm components and capability providers will communicate on. The proposal itself is actually not wasmCloud specific, so it stands on its own. This RFC will primarily focus on the changes necessary to wasmCloud’s RPC to use wRPC instead of wasmbus.

Attempting to sum up the most important points with respect to this RFC:

- Instead of actor components subscribing on an invocation topic of `wasmbus.rpc.<lattice>.<actor_id>`, actor components will subscribe on a wRPC topic that exactly identifies an export specified in the embedded WIT. For `wasi:http/incoming-handler`, this would be `<prefix>.wrpc.0!0!1.wasi:http/incoming-handler@0!2!0.handle`.
    - This `<prefix>` here, as detailed below in Link Routing, will consist of a combination of lattice and actor component identifier or routing group.
- Instead of capability providers subscribing on an invocation topic of `wasmbus.rpc.<lattice>.<provider_id>.<link_name>`, providers will subscribe on a wRPC topic that exactly identifies an export specified in the embedded provider WIT. For `wasi:http/outgoing-handler`, this would be `<prefix>.wrpc.0!0!1.wasi:http/outgoing-handler@0!2!0.request`.
    - This `<prefix>` here, as detailed below in Link Routing, will consist of a combination of lattice, provider identifier, and link name.
- Instead of actor components making requests through wasmbus on a provider invocation topic as mentioned above, actor components will make requests on the wRPC topic as specified as an import in the embedded WIT.
- Instead of providers making requests through wasmbus on an actor invocation topic as mentioned above, providers will make requests on the wRPC topic as specified as an import in their embedded wit.

### Links

Link definitions serve three primary purposes in today’s wasmCloud, all of which must be addressed in the wRPC proposal (in order of increasing complexity for this RFC).

1. Routing
2. Access control
3. Configuration

**************Routing**************

Links will need to change in a few key ways to support an experience that *feels* like composing components over a distributed network. I think it helps to propose the changes in terms of a concrete piece of information, so we’ll start with a link as structured today:

```yaml
{
  "actor_id": "MCF5HVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "contract_id": "wasmcloud:httpserver",
  "link_name": "default",
  "provider_id": "VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M",
  "values": {
    "ADDRESS": "127.0.0.1:8080"
  }
}
```

And here’s the proposed information that would be on the new link structure (in terms of information available), with a few examples to illustrate key changes. In real memory, for efficiency, it would likely be better for this to be composed of hashmaps for efficient lookups:

```json
# Unique target identifier (source identifier must be unique identifier)
{
  "source": "MCF5HVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "target": "VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M",
  "package": {
    "namespace": "wasi",
    "name": "http",
    "version": "0.2.0" # Version would be here, but we may not need it.
  },
  "interface": "incoming-handler",
  "name": "default",
  "config": {}
},
# Actor to actor
{
  "source": "MCF5HVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "target": "MASDHVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "package": {
    "namespace": "evilcorp",
    "name": "analyze",
  },
  "interface": "generate-plan",
  "name": "default",
  # In the case where configuration is supplied, we will attempt to invoke
  # the wasmCloud WIT exported function to provide config to an actor. If the
  # component doesn't need configuration based on a link, then this is a noop
  "config": {}
},
# Actor routing group
{
  "source": "MCF5HVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "target": "myotheractor",
  "package": {
    "namespace": "foo",
    "name": "bar"
  },
  "interface": "baz",
  "name": "default",
  "config": {}
},
# Provider routing group
{
  "source": "MCF5HVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "target": "remotehttp",
  "package": {
    "namespace": "wasi",
    "name": "http"
  },
  "interface": "outgoing-handler",
  "name": "outbound",
  "config": {}
},
# Provider Link
{
  "source": "VCF5HVX5NUCFGDFT5VDRL2OGGINHEXUE7YFKNZZJF7QT222SZYZSMQ6S",
  "target": "remotehttp",
  "package": {
    "namespace": "wasi",
    "name": "http"
  },
  "interface": "incoming-handler",
  "name": "outbound",
  "config": {}
},
```

The key changes above are:

1. A link is now unidirectional between a source and target.
2. A link directly connects a source `import` to a target `export` for a specific package, interface, and version as specified in both the source and target’s WIT.
3. Capability providers do not “run” on a link name anymore, the link name is just a way to allow for identifying different targets for the same package and interface invocation.
4. A link uses a source that is a unique identifier for a specific component **that is the public NKEY that the component is signed with** and target that may be any alphanumeric string, but defaults to a unique identifier to a specific component. This enables the functionality links have today, and it allows for specific advanced use cases for power users. This unique identifier, to preserve the functionality today, could be `<provider_id>`. The **target** is combined with the lattice name to create the wRPC prefix.
    1. When a user starts a component, actor or provider, they may specify any number of additional **routing groups** that are used in addition to the unique nkey identifier that is generated by the host for link targeting. This enables simpler debugging and testing, manual control of routing, better ability to scale, zero downtime upgrades and A/B testing.
        1. Each routing group, uniquely generated or user supplied, adds another topic that the component will accept invocations on. For example, if we start the echo actor component and give it a routing group of `echo`, it will set up invocation listeners on all:
            - `<lattice>.MSDFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5.wrpc.0.0.1.wasi:http/incoming-handler@0.2.0.handle`
            - `<lattice>.echo.wrpc.0.0.1.wasi:http/incoming-handler@0.2.0.handle`
    2. This may not be the permanent solution here, depending on how our signing requirements change and how we decide to uniquely identify components on a lattice.

As routing is the biggest piece of complexity in this RFC, I’ll break down many aspects below access control and configuration (those parts are short, just look! 👇)

****************************Access Control****************************

I propose that a link allows a source component to invoke functionality from the specified interface on the target entity. The presence of a link serves as the intent of an operator at runtime to allow those components to communicate.

**Configuration**

I propose we add the ability to configure a specific component on startup and at runtime, in addition to configuration that must go onto a link definition because it defines information a component needs when invoking / receiving an invocation. This is actually a separate, soon-to-come, RFC. 

**Given the above, and the wRPC protocol proposal, I believe I’ve outlined how link definitions and communication topics must change in order to enable wRPC.** 

## What will the Developers do?

The way we route RPC invocations isn’t something that wasmCloud developers have to think about too hard today. Our core tenet/feature is Seamless Distributed Networking for a reason, and I don’t intend on increasing that complexity for no reason. This section focuses on practically what a user’s declarative Wadm application manifest would look like in the wRPC world, along with a few imperative examples with `wash`.

**The developer will need to be familiar with their component’s WIT world.** As a general rule, we’ve tried to reduce the complexity/reliance on knowing what’s going on under the hood, but this is the most important thing about using Wasm components and must be known. Inspecting this is easy with wash or the wasm-tools CLI, and because it’s always present we can even generate manifests for them to make it simple.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-http-hello-world
  annotations:
    version: v0.0.1
    description: "HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
    experimental: true
spec:
  components:
    - name: http-kv-component
      type: actor
      properties:
        image: file://http-hello-world-component_s.wasm
	    config:
          language: "en-US"
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
        - type: link # Note: rename from linkdef to link
          properties:
	          target: httpclient
            package: "wasi:http"
	          interfaces: 
              - "outgoing-handler"
        - type: link
          properties:
	          target: vault
            package: "wasi:keyvalue"
            name: "secret" # if not specified, "default"
            # Omitting interfaces == link all
						interfaces:
              - "readwrite"
							- "cache"
							..
        - type: link
					properties:
            target: custom-foobar
						package: "mycustom:foobar"
            interfaces: 
              - "baz"
    - name: custom-foobar
      type: actor
      properties:
        image: file://custom_foobar_s.wasm
      traits:
        - type: daemonscaler
          properties:
            replicas: 1

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
				config:
          default_port: 80
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            package: "wasi:http"
	          interface: "incoming-handler"
	          target: http-kv-component
            config:
							port: 8080
    - name: httpclient
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpclient:0.8.0
    - name: redis
      type: capability
      properties:
        image: wasmcloud.azurecr.io/redis:0.8.0
    - name: vault
      type: capability
      properties:
        image: wasmcloud.azurecr.io/vault:0.8.0
```

The above Wadm manifest could automatically be used to generate a directed graph of the relationships specified. For example, manually doing it with excalidraw, we’d have:

![Untitled](https://github.com/wasmCloud/wasmCloud/assets/12040685/3234ff7d-9fe9-4ae7-a544-403a21efb4d8)

As shown above in the manifest you can be specific with an exact interface, or just work at the directional package level to simplify linking each operation to KV for example. All links are defined such that you’re pointing to a target, for simplicity.

Above, we specify a `name` for the link to the vault client. This isn’t necessary in the example, but is needed for any scenario where one component may want to send requests to different components for the same package and interface. The common example we use here is that a component may want to use the `wasi:keyvalue` interfaces for an efficient cache, and the same interfaces for storing secrets. In code, it would look something like this using a wasmCloud API:

```rust
// Pseudocode for how each language would work
wasi::keyvalue::get("count") # redis
// set_target is generated via wit-bindgen
wasmcloud::actor::set_target("secret")
wasi::keyvalue::get("secretcount") # vault
wasi::keyvalue::get("secretcount") # vault
set_target("default") # alternatively, clear_target
wasi::keyvalue::get("othercount") # redis
```

On the imperative side, the number of commands grows as you increase the number of hosts, but with a single host it feels approximately the same. I view the current status quo of complexity with actors/providers/linking to be about the same as this, and recommend that developers use declarative manifests instead for a better experience. That being said, control with imperative commands can enable more advanced use cases or custom operator logic.

```bash
wash up -d --host-seed SNASDASD # Public key NASDASD
wash start actor wasmcloud.azurecr.io/http-kv:0.2.0 \
  --routing-group httpkv \
  --host-id NASDASD
wash config put MASDASDASD language="en-US"
wash start provider wasmcloud.azurecr.io/httpserver:0.78.0 \
  --host-id NASDASD
wash start provider wasmcloud.azurecr.io/redis:0.78.0 \
  --routing-group redis \
  --host-id NASDASD
# Link httpkv -> redis
wash link put MASDHTTPKVID redis --host-id NASDASD
# Link HTTPServer -> httpkv
wash link put VASDHTTPSERVERID httpkv --host-id NASDASD 
wash config put VASDHTTPSERVERID http_kv_port=8080 # Pending wasi:runtime/config proposal
curl localhost:8080

# Alternatively, put outbound links when starting the actor
wash start actor wasmcloud.azurecr.io/other-http-kv:0.2.0 --host-id NASDASD \
  --link wasi:keyvalue redis
wash link put VASDHTTPSERVERID MASDOTHERHTTPKVID --host-id NASDASD 
wash config put VASDHTTPSERVERID other_http_kv_port=8081
curl localhost:8081
```

Linking at the package level preserves the status quo of complexity of linking with wasmCloud contracts as they are today.

### Zero downtime upgrades

Zero downtime upgrades are enabled by **routing groups** that don’t change between different versions of a component. Let’s say I want to upgrade my `http-kv` component from above from 1.2.3 to 1.2.4:

1. Edit Wadm manifest to change reference to the new version
2. `wash app deploy` the new manifest
    1. `wadm` first starts `http-kv` 1.2.4 with the same routing group, `httpkv`
    2. `wadm` then removes the `http-kv` 1.2.3
    3. There is no downtime, because providers send incoming HTTP requests to:
        
        ```bash
        <lattice>.httpkv.wrpc.0.0.1.wasi:http/incoming-handler@0.2.0.handle
        ```
        
        - `http-kv` 1.2.3 and `http-kv` 1.2.4 queue-subscribe on the same topic based on the routing group.

A user is also able to do this imperatively, as that’s what wadm is essentially going to do under the hood.

```bash
wash start actor wasmcloud.azurecr.io/http-kv:1.2.4 --routing-group httpkv
# Requests now are round robining to version 1.2.3 and 1.2.4
wash stop actor wasmcloud.azurecr.io/http-kv:1.2.3 # This will be the unique identifier, not the image reference.

# Upgrades could take care of this in a zero-downtime way as fast as possible
wash upgrade actor wasmcloud.azurecr.io/http-kv:1.2.3 wasmcloud.azurecr.io/http-kv:1.2.4
```

### A/B Testing

Let’s say I want to run my `http-kv` actor from above simultaneously as 1.2.3 and 1.2.4 to verify that 1.2.4 actually works and does not mess up my whole deployment costing me money, customers and mental health.

This case is much more interesting and is accomplished with the following changes to the manifest above:

1. Rename `http-kv` 1.2.3 to `http-kv-old`
2. Add `routing_groups` property equal to `httpkv` to `http-kv-old` definition
3. Add `http-kv-new` definition, which is almost identical to `http-kv-old`, except for the image version
4. Run `wash app deploy`
    1. There is no downtime, due to the same reasoning as above, requests from providers are still sent on `<lattice>.httpkv` prefix.
5. Once happy with the state of affairs, I:
    1. Remove `httpkv-new` `routing_group` from `http-kv`
    2. Remove `http-kv-old` entirely
    3. Run `wash app deploy`
        1. There is no downtime, see upgrades section above.
        

Here’s the example of what my actor definitions after step 3. look like:

```yaml
  - name: http-kv-old
    type: actor
    properties:
      image: wasmcloud.azurecr.io/hello:1.2.3
			routing_groups:
			#- "httpkv"
      # If desired, you can invoke the older version to test functionality/backwards compatibility
			- "httpkv-123"
			config:
				motd: "hello world"
        target: "httpkv-123"
		traits:
      - type: spreadscaler
        properties:
          instances: 90
          spread:
            - name: eastcoast
              requirements:
                zone: us-east-1
              weight: 80
            - name: westcoast
              requirements:
                zone: us-west-1
              weight: 20

	- name: http-kv
    type: actor
    properties:
      image: wasmcloud.azurecr.io/hello:1.2.4
			routing_groups:
			# - "httpkv"
      # If desired, you can now invoke the new version on its routing group to test new functionality
			- "httpkv-124"
			config:
				motd: "hello world"
		traits:
			# I may also want to only deploy this version in
      # select regions and/or with limited weights for testing
      - type: spreadscaler
        properties:
          instances: 10
          spread:
            - name: eastcoast
              requirements:
                zone: us-east-1
              weight: 80
            - name: westcoast
              requirements:
                zone: us-west-1
              weight: 20
```

### Future Security

This RFC is primarily focused on putting the protocol into practice and the changes needed to links to make it work. We heavily considered the way that we could add additional security to this, and though it won’t be done in the initial implementation we now have the baseline for enabling encryption-in-transit for invocations. Additionally, concepts like invocation signing and validation can be added without affecting the proposal as the protocol is transport agnostic.

In cases where I want my traffic to be encrypted, or simply link plaintext traffic towards a public key, I could do something like this:

```yaml
- name: hello-encrypted
  type: actor
  properties:
    image: wasmcloud.azurecr.io/hello:1.2.3
		key: ./path/to/private/nkey # public key MABCDEF

- name: rand-encrypted
  type: actor
  properties:
    image: wasmcloud.azurecr.io/rand:3.2.1
		key: ./path/to/private/nkey # public key MGHIJKLMNOP

- name: super-secret
	type: actor
	properties:
		image: wasmcloud.azurecr.io/shhhhh:0.1.0
  traits:
	  - type: link
			properties:
				target: hello-encrypted
				package: "wasi:http"
				interfaces:
					- incoming-handler
				encryption:
					algo: nkey

		- type: link
			properties:
				target: rand-encrypted
				package: "wasi:rand"
				interfaces:
					- rand
				encryption:
					algo: nkey
```

My actor components listen on `<lattice>.$PUBKEY.wrpc.>` when a key is specified, private key is sent encrypted to the hosts using the respective hosts public key, which always exists. This does require that hosts in a lattice that participate in encryption share a NKEY private key which is supplied at host start time and is only ever kept in-memory (which will be well worth using a crate like [secrecy](https://crates.io/crates/secrecy) to provide better guarantees of memory secrecy).

The actor components themselves will not be responsible for encrypting or decrypting messages, it’s done automatically by the host if the host is configured to do so. The reason why we supply keys per-component is because we want to be able to encrypt traffic specifically with a component’s nkey, not just a single host nkey. Component private keys would be encrypted and decrypted using the hosts nkey to avoid sending or storing plaintext information.

As usual there’s more to explore here, and I would ask that we not get too hung up on this particular aspect of this RFC unless you see glaring issues that will make it impossible. I do not propose we implement encryption until at the earliest wasmCloud 1.1.0.

### Backwards Compatibility

- In order to preserve backwards compatibility with our WASI 0.1.0 modules that are generated from Smithy interfaces and use the wasmbus RPC protocol, we should have these components (actors and providers) still operate using wasmbus RPC. In the interest of reducing complexity, I do not believe we need to support Smithy based components communicating with wRPC components. Put another way, workloads can function as they do today, but wasmbus is officially deprecated and will only receive updates to patch security issues.
- As all WIT interfaces are strictly versioned, we are able to control handling multiple versions of WIT interfaces as we move forward past wasmCloud 1.0. To mitigate this, though, we will pin our wasmCloud WIT interfaces to @1.0 before we cut the release, and pin all WASI interfaces to their @0.2.0 version to maximize the stable foundation of our release.
- As the wRPC protocol is strictly versioned on the topic, we can support protocol upgrades if necessary over time.

### Alternatives Considered

- The biggest alternative that we could enforce is simply continuing to support wasmCloud contracts and polyfilling WebAssembly component interfaces. This would reduce work in the short term and preserve more of the status quo. I strongly believe that this is not a path forward if we are to fully support WebAssembly components, as solving this for specific interfaces is simple but we would never be able to support custom WIT interfaces over the lattice.
- Another alternative we could consider is using some wRPC and some wasmbus communication to simplify the RPC layer. Though this may smooth migration to wRPC, I feel this increases the technical burden of the project without gaining us much.

### Unresolved Questions

- There are many WASI interfaces that we’re going to satisfy automatically with the wasmCloud host. Interfaces in the `wasi:cli`, `wasi:clocks`, `wasi:sockets`, etc packages are likely to never need a distributed lattice component to satisfy at runtime.
    - How do we define that set of packages that the user does not need a link for?
    - Do we allow users to override links for that “builtin” set of packages, e.g. sending `wasi:logging/log` invocations to their own logging implementation? (I think yes)
    - Do we want to extend this set of “builtin” packages, including things like wasi:http incoming and outgoing handler, so that components can work out of the box? (I think yes)
- When Wadm is linking components together, how do we work with generated unique IDs and defining links to enable round robin scaling by default?
- Will supporting wasmbus and wRPC at the same time take too much effort? If so, is it an acceptable compromise to drop support before 1.0.0?
- I do feel that `set_target` should use a link name in order to provide the best flexibility, could we consider renaming that to `set_link` or `set_link_name`? I don’t want to solely provide the target because it keeps it simpler for us to consider the link name as default for all scenarios where a component is off-the-shelf, e.g. did not use wasmCloud APIs before. If we do drop the link name and allow people to set the target directly, that means they either must use a unique identifier or use routing groups which I’d prefer to leave for more advanced use cases.
- 
## Notes

- [Just a note that NATS recommends limiting topics to 16 tokens max, which we do not exceed 10](https://docs.nats.io/nats-concepts/subjects#subject-tokens) in the proposal. [There is no limit on the number of subjects we can register.](https://docs.nats.io/reference/faq#does-nats-impose-any-limits-on-the-of-subjects)
- Future evolutions of capability providers like wasmtime host plugins will be supported by this RFC as we are slowly pushing provider RPC to have the same subscriptions, format and protocol as component RPC.

### Conclusion

**************************************************We want wasmCloud RPC to feel like composing components, at runtime, over the lattice.**************************************************

Using the above proposed combination of the wRPC protocol and unidirectional links on the Wasm interface level, we can compose components at runtime over our distributed lattice network. There are significant breaking changes in this proposal and it will take a large amount of effort to complete the migration to wRPC. That being said, I intend to allow for workloads that function today to continue to function, albeit in a deprecated state and to be removed in wasmCloud 2.0.0.

This RFC came from many, many hours of design and consideration when it comes to links and the protocol from myself, @rvolosatovs, @thomastaylor312, and @connorsmith256. As a 4+ year maintainer of wasmCloud, I see this as a wonderful evolution of this project and I’m excited to hear feedback, especially critical, on this key set of changes. Just to reiterate, this enables componentized applications to communicate over the lattice, and there may be more changes to links, routing groups, etc in the future pre and post 1.0 for the best wasmCloud experience.
