### ISSUE TITLE
[BUG] Custom wash build command breaks JSON output

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1400]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

With a custom `build_command` under the `[actor]` section in wasmcloud.toml, we somewhere print to stdout `Component built successfully` before the actual command output. When run with JSON output, this causes a broken pipe error as it's not valid JSON.

I ran into this when getting #1399 together

```toml
name = "python-http-hello-world"
language = "python"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:httpclient", "wasmcloud:httpserver"]
build_command = "componentize-py -d ./wit -w hello componentize app -o build/http_hello_world.wasm"
build_artifact = "./build/http_hello_world.wasm"
destination = "./build/http_hello_world_s.wasm"
```

```shell
➜ wash build -o json
Component built successfully

{
  "actor_path": "/Users/brooks/github.com/wasmcloud/wasmCloud/examples/python/actors/http-hello-world/./build/http_hello_world_s.wasm",
  "signed": true,
  "built": true,
  "success": true
}

➜ wash build -o json | jq
parse error: Invalid numeric literal at line 1, column 10
thread 'main' panicked at library/std/src/io/stdio.rs:1019:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps to reproduce

1. Add a custom build command to a component's wasmcloud.toml
2. Run `wash build -o json`
3. View extra output

### Expected behavior

I expected for it to be just JSON output and to pipe directly into JQ	

### Environment

- OS: MacOS
- Shell: zsh
- wash Version: 0.25.0
