### ISSUE TITLE
[BUG] The directionality of the NATS messaging provider link is inverted

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1882]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

In #1881, I had to define my link from the echo component to NATS like so:
```
    - name: echo
      type: component
      properties:
        image: file://./build/echo_messaging_s.wasm
        id: echo
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
            target_config:
              - name: simple-subscription
                properties:
                  subscriptions: wasmcloud.echo
```

This is correct for the link on the `consumer` interface, but I should not set up subscriptions using this link. This should be a link that configures all of the publish and request operations that the component will do.

The NATS messaging provider is meant to invoke a component based on a subscription. The way you _should_ specify a link from the NATS provider to a component is like this (in wadm):
```yaml
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        - type: link
          properties:
            target: echo
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: simple-subscription
                properties:
                  subscriptions: wasmcloud.echo
```

The configuration here should be the source configuration, since you're configuring NATS to subscribe and then invoke the component's `handler.handle-message` function. This should be fairly easily changed inside of the provider, we should be receiving link configuration both as a source and as a target to do the different setups.

### Steps to reproduce

The fact that you can use the manifest in https://github.com/wasmCloud/wasmCloud/pull/1881 to create a subscription is just slightly wrong, so deploying that is the issue.

### Expected behavior

All in all, the correct manifest should look like this (component -> NATS on `consumer`, NATS -> component on `handler` with subscription information):
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-echo-messaging
  annotations:
    version: v0.0.1
    description: "Echo demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
spec:
  components:
    - name: echo
      type: component
      properties:
        image: file://./build/echo_messaging_s.wasm
        id: echo
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    # Add a capability provider that implements `wasmcloud:messaging` using NATS
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        - type: link
          properties:
            target: echo
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: simple-subscription
                properties:
                  subscriptions: wasmcloud.echo
```

It is slightly more verbose to have to do both directions on the link, but it's correct! 😄 It's important that we're separating the concerns on the links here since the ability to publish and to receive are different attestations on the operator side.

### Environment

- OS: [e.g. Linux, MacOS] MacOS
- Shell [e.g. bash, zsh, powershell] zsh
- wasmcloud Version [e.g. 0.81.0] 1.0.0-rc.1
