### ISSUE TITLE
[RFC] Single process multi-tenancy support

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#195]
## Background

The way wasmCloud uniquely identifies actors is by their public key. The public key is a direct correlation to the private key that was used to sign the module. This generally means that whenever people are building their own actors, the actors will have unique public keys and will therefore never interfere with each other. 

wasmCloud assumes that if a given actor occurs multiple times within the same lattice (or eventually within the same host once we support #54 local actor pools). Essentially the actor's public/primary key is the unit of horizontal scaleout uniqueness. If I want to run 5 copies of my actor, then all 5 of those copies are considered horizontally scaled actors and _must be identical_ - including their configuration. This is the same concept as increasing the scale count of a **pod** - Each of those pods _must_ have been created with the _same_ **podspec**, otherwise the horizontal scale group will be internally inconsistent.

## The Problem

The problem is with multi-tenancy within a single host process. We never really considered the edge case that multiple different owning entities would ever want to run the same actors in the same host but with different configurations. However, this is actually a pretty common multi-tenant scenario, as evidenced by [krustlet](https://krustlet.dev/)'s use of a single wasmCloud host runtime _per node_ (and not _per pod_). 

Easy steps to reproduce the problem:
1. Follow any of the tutorials and add/start the `echo` actor in a wasmCloud host process
1. Bind that `echo` actor to port `8080` of the HTTP server provider.
1. Now, a second _tenant_ also follows the same tutorial, and wants to add the `echo` actor to the host.
    1. Even if you _could_ add the actor twice (which you currently cannot), the host would assume this is a _horizontal scaleout_ operation, and _not_ a multi-tenant operation.
1. Now you have two `echo` actors running in the same host. You cannot then bind the echo actor to the HTTP server provider with port `8080` for _tenant 1_ and port `8081` for _tenant 2_.

## Proposed Solution

The proposed solution to this multi-tenant problem would be to give actors a second field in a composite key. Capability providers already have this, where they have both a public key and a link name. Actors could be started with a `group id`. This group ID would be part of that actor's unique identifier. Horizontal scale-out of an actor would then occur for the combination of the actor's public key _and_ its group ID. Dispatch from capability providers to actors would be done through the new composite key of public key + group ID. Link definitions would _optionally_ be able to specify the source actor's group ID (if left off, the group ID would be assumed to be `default`). This would enable the scenario where two different copies of the same exact echo actor could be running inside the same wasmCloud host _with different configuration bindings_, while still enabling each of those actors to horizontally scale _independently_.

This would operate very much like the concept of a `queue group` in message broker terminology. If no group ID is specified at the time an actor is started, then it would use `default`, just the way capability providers do. This would provide some measure of backwards compatibility in that scenarios that don't require strict multi-tenancy would continue to operate just fine as if nothing had changed.

**Comment by autodidaddict** [comment]
Here's what a new manifest might look like with multi-tenant actors:

```yaml
---
labels:
    sample: "Multi-tenant Echo"
actors:
    - image_ref: wasmcloud.azurecr.io/echo:0.2.0
      group_id: tenant1
    - image_ref: wasmcloud.azurecr.io/echo:0.2.0
      group_id: tenant2
capabilities:
    - image_ref: wasmcloud.azurecr.io/httpserver:0.1.0
links:
  - actor: ${MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5}
    actor_group: tenant1
    contract_id: "wasmcloud:httpserver"
    provider_id: "VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M"
    values:
      PORT: 8080
  - actor: ${MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5}
    actor_group: tenant2
    contract_id: "wasmcloud:httpserver"
    provider_id: "VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M"
    values:
      PORT: 8081
```
