### ISSUE TITLE
[FEATURE] Support link source/target configuration for components

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2170]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Links currently contain two fields, `source_config` and `target_config` for specifying configuration that should be available to either the source or the target of the link, respectively. Currently, this configuration is not merged with a component's configuration, so source/target configuration that should be given to a component is currently just a noop.

The motivation for this separation is to be able to define exactly which component or provider should have access to a piece of configuration. In a relationship where a component targets a provider, say my-sql-component -wasmcloud:postgres-> postgres, the postgres provider should be able to read the connection string but the component doesn't need it at all, and we shouldn't be giving the component access to that information (this is especially relevant in the secrets discussion #2060)

### Describe the solution you'd like

When a link is created where the component is the source, we should fetch that configuration and merge it with that component's configuration map. If we are going to support this, then we don't know what links a component is going to use, so we'll need to provide the entire source configuration.

When a link is created where the component is the target, we should fetch that configuration and merge it with that component's configuration map _when a request comes in on that link_. For example, say we have a wadm manifest like so:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-hello-world
  annotations:
    version: v0.0.1
    description: "HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/http_hello_world_s.wasm
        config:
          - name: component-response
            properties:
              LANG: "EN_US"
              status: "200"
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
            target_config:
              - name: default-response
                properties:
                  status: "404"
                  message: "oopsies, page not found"
```

When the HTTP handler is invoked on the component, the configuration should be as follows:
```json
{
  "status": "404",
  "message": "oopsies, page not found",
  "LANG": "EN_US"
}
```

However, if a different handler were invoked on that component, then the configuration should be:
```json
{
  "status": "200",
  "LANG": "EN_US"
}
```

This should allow us to fine tune the configuration for a component, especially when it comes to invoking a component with the same interface but a different link name.

### Describe alternatives you've considered

We could only support source/target config for providers, but that seems like it cuts out valuable use cases 🤔 

For anyone working around this now, configuration can pretty much be put inside of the component's config and there's not much difference with how we'd implement this.
