### ISSUE TITLE
[RFC] Secrets in wasmCloud

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wasmCloud#2190]
### RFC Title

RFC: Secrets in wasmCloud

### Introduction

The goal of this RFC is to propose a new API specification for *secrets backends*, which are programs that will listen on NATS for requests for secrets and be able to satisfy them. This RFC also outlines changes to the wasmCloud host opt in to the feature and to connect to these secret service backends in order to provide secrets to components and providers. This new API is designed so that many secrets backends can be connected to a wasmCloud cluster so that end applications can use multiple secrets providers at runtime.

### Motivation

Production applications often require secrets at runtime to access internal or external systems. Up until now our only option for providing secrets was to link a component to a capability provider such as the Vault KV provider that could access secrets. This approach has several drawbacks:

- You must run a dedicated provider for ex. Vault that need their own secrets in order to connect to upstream providers.
- Secrets need to be retrieved every time a component or provider needs them which can be inefficient.
- Secrets management is tightly bound to a single provider and interface type, which means that the component's implementation is irrevocably tied to it. This violates the spirit of what wasmCloud is trying to solve for adopters and makes it difficult to develop applications that consume secrets.

## Objectives

- Outline a new NATS-based API for secrets backends. A wasmCloud cluster *must* have a running secrets backend in order to provide secrets to components and providers. A wasmCloud cluster *must* support multiple secrets backends running at the same time.
- Define the changes to the host required to implement support for securely retrieving secrets from a secrets backend.
- Define a WIT interface used for retrieving secrets from a host.
- Outline the necessary changes to a wadm manifest to allow for secrets support in target and source configurations.

The implementation of this RFC will result in a reference implementation based on a NATS Key Value secrets service backend. In addition, we will also work on additional secret backends, including Vault, OpenBAO and others. We may opt to include the NATS KV-backend as part of Wadm, enabled by passing in a flag and a xkey used for encrypting the underlying NATS KV bucket.

## Design
Secrets are intended to be very similar to config in wasmCloud, except that they are explicit *references* to data that lives outside of the wasmCloud cluster. It is the host's responsibility to retrieve secrets from a secrets backend and provide them to components and providers that request them. Secrets backends will be reachable by hosts via NATS using known NATS subject prefixes. Each secrets backend will satisfy a common API so that anyone can write a backend and add an implementation to their cluster.

A secrets backend implementation will be identified by a single string as a name and will receive credentials requests on a NATS subject that includes this name prefix. The canonical default root prefix for the subject will be `wasmcloud.secrets`. A specific deploy of a secrets backend will be required to set a unique name for the backend and will listen for requests on the subject `wasmcloud.secrets.$backend.>`.

As an example, assume that there is a NATS KV-backed secrets backend and a Vault-backed secrets backend running as part of a wasmCloud cluster. The NATS KV secrets backend is configured with the name `nats-kv` and the Vault backend is predictably named `vault`. The following table shows the NATS subjects that each backend will listen on:

| Name | Subject |
| --- | --- |
| vault-prod | wasmcloud.secrets.vault-prod.> |
| vault-dev | wasmcloud.secrets.vault-dev.> |
| vault-customer | wasmcloud.secrets.vault-customer.> |

Each of the secrets backend services subscribed to each subject might use the same underlying secrets-backend implementation, but identified with a different name

Secrets backends are currently intended to be implemented as binaries that run alongside the wasmCloud cluster, similar to how Wadm is deployed. We considered implementing them as providers in a privileged set of wasmCloud hosts, but felt that provided no real benefit other than being able to use Wadm to deploy and manage their lifecycle.

### Secrets Backend Security

Secrets backends *must* only dispense secrets to hosts that are making requests on behalf of components and providers. We can take advantage of the fact that components and providers are are signed as part of the build process when running `wash build`. Both types of workload are signed with an account nkey, which we can use to validate the identity of of the workload making the request and use that fact to map secrets that are scoped to be accessed by that workload. A secrets backend *must* be able to authenticate a signed JWT from the requesting host that identifies the workload. The secrets backend *must* also be configured with a map of that workload to a set of secrets that it is allowed to access. This will likely be very different across different secrets backends, since it will likely be implementation specific.

Let's explore the idea of having a sample NATS KV-backed secrets backend along with a Vault backend. In order to satisfy the mapping requirement, the NATS backend exposes a few new API endpoints that allow an administrator to add these mappings:

| Endpoint | Parameters | Description |
| --- | --- | --- |
| wasmcloud.secrets.nats-kv.add_mapping | `{"account": "ADQ4EBYYQDYANINHZOTCOOKXCJ6C75YXCVMACM456N6QARKHVFJ7TA4V","entity": "MCQSWZZPZVMJB2LQ2OZ3TCBX5ZBVNOUDSGVCA5MIZUFHB5SHV2RRLA7I", "secrets": ["value1", "value2"}` | Add a mapping of a workload to a set of secrets |
| wasmcloud.secrets.nats-kv.remove_mapping | `{"account": "ADQ4EBYYQDYANINHZOTCOOKXCJ6C75YXCVMACM456N6QARKHVFJ7TA4V","entity": "MCQSWZZPZVMJB2LQ2OZ3TCBX5ZBVNOUDSGVCA5MIZUFHB5SHV2RRLA7I"}` | Remove a mapping of a workload to a set of secrets |

The above API endpoints would be used by an administrator to add and remove mappings of a workload to a set of secrets stored as a keys in a NATS KV bucket. The secrets backend would verify that the signature of the JWT was signed by the account identified by its issuer (the `iss` field), and having done so will look up the mappings it has store in order to determine if the workload is allowed to access the secret identified on a request.

On the other hand, a Vault-backed implementation might behave entirely differently because we can take advantage of Vault's built-in policies and [JWT authentication](https://developer.hashicorp.com/vault/api-docs/auth/jwt#configure) to validate the JWT and return a Vault token bound to a workload-specific policy. This will be our recommended pattern for Vault and will be used to build the reference implementation. Other Vault-backed implementations may choose to use a different method of mapping secrets to workloads, for instance by using OIDC to map a workload to a Vault policy, using a custom plugin, etc.

Restricting access to secrets backends can be handled by using NATS distributed auth to issue hosts with NATS credentials in an account that either only allows them to access specific backends or blocks them entirely.

### Secrets Backend API

The secrets backend API is a NATS-based API that is used to retrieve secrets from a secrets backend. The API is defined as follows:

```rust
#[derive(Serialize, Deserialize)]
struct Context {
    // The component or provider's signed JWT.
    jwt: String,
}

struct SecretRequest {
    // The name of the secret
    name: String,
    // The version of the secret
    version: Option<String>,
    context: Context,
}

struct Secret {
    pub name: String,
    pub version: String,
    pub string_secret: Option<String>,
    pub binary_secret: Option<Vec<u8>>,
}

struct SecretResponse {
    pub secret: Option<Secret>,
    pub error: Option<String>,
}
```

One of the key properties of this API is that we are  encrypt sensitive payloads in transit in NATS using *xkeys*. Xkeys are x25519 keypairs that are an extension on top of NATS’ nkeys format. These keys are compatible with the [NaCl](https://nacl.cr.yp.to/) Seal and Open operations, which makes them suitable for general purpose encryption and decryption.

The payload of a request to the `wasmcloud.secrets.$name.get`endpoint *must* be encrypted using a xkey generated by the host for that specific request and provided as a header on the NATS message. This is to prevent replay attacks and eavesdropping by other NATS clients on the secrets backend. If the payload of a get request was sent in the clear, in theory all a malicious client would need to do in order to get a copy of secrets for a component or provider would be to resend the original request. While the signed component or provider JWTs are *not* private, having a copy of them does demonstrate that the caller has access to the built binary and accessing secrets on their behalf. Encrypting the payload with a single use xkey prevents the need for a nonce or a timestamp since every request to the endpoint has a unique payload.

 The `server_xkey` endpoint is used to retrieve the public xkey of the secrets backend so that the host can encrypt and decrypt communication to the backend. Callers *should* cache this key so that they do not have to make repeated calls to the endpoint before calling `get`. If the server is unable to decrypt a payload it will return an error indicating that, so clients should make a call to the `server_xkey` endpoint to refresh the server’s key and try again. We might able to mitigate this in the future by providing secret backend keys using the config service, but that may be an improvement for a future RFC.

### Get request payload

Headers:

- `Wasmcloud-Host-Xkey`: String

Body:

```json
{
    "secret_name": "",
    "version": "1",
    "context": {
        "jwt": "..."
    }
}

```

### Get response payload

```jsonc
{
  // Will be empty if errored
  "secret": {
    "name": "",
    "version": "",
    // Only one of the following fields will be set
    "secret_string": "",
    "secret_binary": ""
    }
    // Omitted on success
    "error": ""
}

```

A successful response will only contain the `secret` payload. An unsuccessful response will contain an `error` key with a string message describing the error. This will likely be implemented using an enum, so we could encode this as a JSON object that contains an error code and a message instead. Examples of what might cause an error include:

- An invalid source JWT (component or provider)
- Secret not found
- Errors encrypting or decrypting the secret
- Some error with the backend

Secrets backend implementations may also have additional API endpoints as needed. An example of this might be mapping secrets to specific components or providers in ex. the the sample NATS KV-backed implementation.

The full path of a request can be seen in this diagram: 

![wasmCloud Secrets Backend Retrieval Process](https://github.com/wasmCloud/wasmCloud/assets/308328/75fbe454-768a-4e56-8288-9b552aa8baa5)

### wasmCloud Host Changes

Secrets support is intended to be an opt-in feature. The host will enable secrets support by setting the `WASMCLOUD_SECRETS_SUBJECT` (`--wasmcloud-secrets-subject`) environment variable. This subject is the prefix that all secrets services will be listening on for requests. If this value is *not* set then requests to start a wasmCloud application that requires secrets will fail.

The host will need to generate a request-specific xkey when calling out to a backend secrets service to retrieve secrets on behalf of a workload. This will allow the host to encrypt and decrypt payloads between the host and the secrets backend. Each request and response to a secrets backend to retrieve secrets *must* be encrypted in order to prevent replay attacks and eavesdropping.

The host will also need to handle retrieving requests for secrets from a component or a provider *before* instantiating either of them. This is to prevent starting a component or a provider that will immediately fail to execute due to not being able to access secrets. This should be reported as a `Failed` status for an application when a secret is depended on in a Wadm manifest.

The host must securely cache secrets so that it doesn’t need to retrieve secrets on every invocation of a component. 

### WADM Manifest

Components and providers will need to specify which secrets they require as part of their manifest definitions. A secret can be defined in two different places: at the top level of a component or a provider, at the same level as `config`, or in the configuration of a link. This gives us the opportunity to distinguish between the two contexts and have the host merge them together as needed.

### Secrets Spec

```rust
struct Secret {
    // The name of the secret
    name: String,
    // The source of the secret
    source: Source
}

struct Source {
    // The backend of the secret
    backend: String,
    // The value of the secret
    value: String,
    // The version of the secret
    version: Option<String>
}

```

### Entity-scoped Secrets

An entity-scoped secret is a secret that is defined at the top level of a component or provider. This means that the secret is available in any function defined by a component, including those that are implemented to handle a specific interface attached to a link. This is useful for secrets that are used across multiple interfaces or functions.

```yaml
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/wasmcloud/test-fetch-with-token:0.1.0-fake
        secrets:
          - name: some-api-token
            source:
              backend: vault
              key: secrets/test/value
              version: 1
          - name: my-other-secret
            source:
              backend: aws-secrets-manager
              value: secret-name
              version: "be01a5fb-7ebb-4ae9-8ea0-0902e8940bc0"

```

### Link-scoped Secrets

A link-scoped secret is only accessible in the context of a link. For a component, this means that it is only available in the functions that are implemented to handle the interfaces that defined by the link. For a provider, this means that is supplied when the link is created. This is intended for secrets such as database connection strings, API tokens, etc, that are needed in the context of a component communicating with another component or a provider. An example of what this looks like is shown below:

```yaml
        - type: link
          properties:
            namespace: wasmcloud
            package: postgres
            interfaces: [managed-query]
            target:
              name: sql-postgres
              secrets:
                - name: db-password
                  source:
                    backend: vault
                    key: secrets/myapp/db-password
                    version: 1

```

### Secrets Sources

An alternative syntax for condensing the secrets source is represented below, which uses a URI to identify the secrets source:

```yaml
secrets:
    - name: my-secret
      source: vault://secrets/test/value
    - name: my-other-secret
      source: aws-secrets-manager://secret-name
    # Can have many sources that talk to different backends but the same provider:
    - name: my-third-secret
      source: my-other-vault://secrets/test/value

    # Not prefixed with a source if we decide not to support that
    - name: my-third-secret
      source: secret-name

    # Versioning
    - name: my-fourth-secret
      source: vault://secrets/yet-another-secret
      version: 3
```

We can use this alternative representation if we prefer, but breaking the source up into different parts is more clear at the cost of adding additional levels of YAML.

### Sample Manifest

Below is a sample manifest that shows how secrets can be defined in a wasmCloud application:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: App with secrets
  annotations:
    version: v0.0.1
    description: "HTTP hello world demo in Rust, showing use of the server and client providers"
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/wasmcloud/test-fetch-with-token:0.1.0-fake
        secrets:
          - name: some-api-token
            source:
              backend: vault
              key: secrets/test/value
              version: 1
          - name: my-other-secret
            source:
              backend: aws-secrets-manager
              key: secret-name
              version: "be01a5fb-7ebb-4ae9-8ea0-0902e8940bc0"
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]
        - type: link
          properties:
            namespace: wasmcloud
            package: postgres
            interfaces: [managed-query]
            target:
              name: sql-postgres
              secrets:
                - name: db-password
                  properties:
                    backend: vault
                    key: secrets/myapp/db-password
                    version: 1
              config:
                - name: foo
                  properties:
                    value: whatever

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            target:
              name: http-component
              secrets: ...
            source:
              config:
                  - name: default-http
                    properties:
                      address: 127.0.0.1:8080
              secrets:

    - name: httpclient
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.9.0

    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/provider-sqldb-postgres:0.1.0
```

Note that there is one other change being proposed to the manifest format here: merging what we have defined now as `target_config` and `source_config` into the `target` and `source` properties. This is to avoid the need for `target_secrets` and `source_secrets` properties, along with being an opportunity to clean up what was previously a confusing way of referring to those concepts.

For a `target`, this means we will need to modify Wadm's parser to handle the case where a `target` is supplied either as a string (the current format) or as a struct in the new format. Not handling that will result in a breaking change to the manifest format, so if we want to

### WIT

The WIT interface for secrets is almost the same as `wasi:config` only with a small change to the `get` function and the removal of the `get-all` function.

```wit
interface store {
    /// An error type that encapsulates the different errors that can occur fetching secrets
    variant secrets-error {
        /// This indicates an error from an "upstream" secrets source.
        /// As this could be almost _anything_ (such as Vault, Kubernetes Secrets, KeyValue buckets, etc),
        /// the error message is a string.
        upstream(string),
        /// This indicates an error from an I/O operation.
        /// As this could be almost _anything_ (such as a file read, network connection, etc),
        /// the error message is a string.
        /// Depending on how this ends up being consumed,
        /// we may consider moving this to use the `wasi:io/error` type instead.
        /// For simplicity right now in supporting multiple implementations, it is being left as a string.
        io(string),
    }

    variant secret-value {
        /// A string value
        %string(string),
        /// A byte array value
        bytes(list<u8>),
    }

    resource secret;

    /// Gets a single opaque secrets value set at the given key if it exists
    get: func(
        /// A string key to fetch
        key: string,
    ) -> result<secret, secrets-error>;
}

interface reveal {
  use store.{secret, secret-value};
  reveal: func(s: borrow<secret>) -> secret-value;
}
```

A component call to the host will look something like the following in Rust:

```rust
use wasmcloud::secrets::{store, reveal};

// ...
fn work() -> anyhow::Result<()> {
    let secret = client::get("my-secret")?;
    let value = reveal.reveal(secret);
}
```

### Backwards Compatibility

Secrets support is intended to be an opt-in feature. The host will enable secrets support by setting the `WASMCLOUD_SECRETS_SUBJECT` (`--wasmcloud-secrets-subject`) environment variable. This subject is the prefix that all secrets services will be listening on for requests. If this value is *not* set then requests to start a wasmCloud application that requires secrets will fail.

Going forward we might want to make this a required feature _or_ provide a default implementation that can be deployed in wasmCloud clusters for evaluation purposes. This might be as simple as adding a new binary to `wash up` and leaning on operators to decide on which secret service backends they want to run in production clusters.

### Pluggable secrets providers in Wadm

Wadm is ubiquitous in a production-grade wasmCloud deployment, so why not have it handle secrets requests? This would allow for a more seamless experience for end users, as they could use the same tool to manage secrets as they do to manage wasmCloud applications and would be one less container or binary to deploy. However, the usual challenges of how to build a plugin system and whether or not you need to deploy plugins alongside Wadm suggest that this isn't the best way to handle it. We debated the idea of building plugins as components, but unlike wash plugins we would need to bundle in host-level capabilities to communicate with NATS or an unknown amount of third-party systems and protocols, which feels like more effort that it is worth. We may want to revisit that in the future as WASI evolves we have features such as threads at our disposal.

### Secrets as a capability provider

As discussed previously, this idea is tempting because you could manage secrets backends with the same tools that we use to deploy normal wasmCloud applications. The biggest reason to not do this is that secrets backends will likely require their own secrets as well. Unless we wanted to settle on some out of band secure secrets management features that only these providers would have available (ex. a dedicated NATS KV implementation), there doesn't seem to be enough of a benefit to running them as providers.

### Do nothing

We have heard from users in the community that while config values are a decent stopgap, we absolutely need secrets management as a first class feature in wasmCloud. The current approach of using config values to store secrets is inherently insecure, and the distinction between config and secrets is one that needs to be maintained. There is plenty of prior art as to separating the two concepts in other orchestration systems (ex. Kubernetes Secrets vs ConfigMaps, Nomad, etc.).

### Unresolved Questions

* This RFC continues the trend of centralizing opt-in services as cluster-wide resources forming more of a control plane for wasmCloud. I think this is the right direction, but it's something that we should agree on.
* Should wadm play more of a role as a coordination layer these cluster-wide APIs (policy service, config service, now thje secrets service)?
* Should we implement the ability for wash to manipulate secrets in a secrets service? I opted not to in this round since we should prove out the idea first and see if anyone asks for that ability, but it might be worth discussing further.
* Should we account for versioning in the API? We have prior art in the control interface now, but there may be other ways to handle that (ex. versions in headers)

### Conclusion

This RFC proposes a new API for secrets backends and would give us the ability to securely handle secrets on behalf of any wasmCloud application. We know this is causing pain for early adopters of wasmCloud, so ideally I'd like feedback on this soon so that we can implement the feature.
