### ISSUE TITLE
[BUG] Otel traces are only getting generated for the http-server provider

### ISSUE THREAD

**Issue by ritesh089** [wasmCloud/wasmCloud#2263]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I used the following environment variables to setup traces using otel and jaeger .

```
export WASMCLOUD_OBSERVABILITY_ENABLED="true"
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318
wash up
```

I created the following link
http-server(provider) --> component --> http-client(provider)

Otel config:

```
receivers:
  otlp:
    protocols:
      http:

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      
     ```
      
     But when i make a call to my component via the http server and check the traces, I only see a span for the http server capability provider .
     Traces for component and http client are missing.
 

### Steps to reproduce

export WASMCLOUD_OBSERVABILITY_ENABLED="true"
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318
wash up
 
Create a component , wash build
 
wash app deploy
 
send a http request using curl .
 
Open jaeger at http://localhost:16686/ to view the traces.
 
 
Docker-compose :
```

version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  otel-collector:
    image: otel/opentelemetry-collector:0.33.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55680:55680"
      - "55678:55678"
      - "55679:55679"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: \["--config=/etc/otel-collector-config.yaml"\]

```

### Expected behavior

I expected to see the trace to contain spans for http-server, component and http-client

### Environment

- OS: MACOS
- Shell : zsh
- wasmcloud Version :0.28.1

```
