### ISSUE TITLE
[FEATURE] Support debug compilation for Rust with wash build

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2298]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Building release mode binaries takes a significantly longer time than building debug mode binaries for Rust. When rapidly iterating on a capability provider, always having to build in release mode slows down the feedback loop.

### Describe the solution you'd like

I would love to be able to specify in my `wasmcloud.toml` file to build for debug mode instead of release for Rust providers. For example:
```toml
name = "Messaging NATS"
language = "rust"
type = "provider"
version = "0.20.0"

[rust]
target_dir = "../../"
# Added field
debug = true

[provider]
bin_name = "messaging-nats-provider"
vendor = "wasmCloud"
```

This `debug` field could default to `false` and when it's false build for release. We could use this for components as well.

### Describe alternatives you've considered

We could make debug the default, but that would be a change in behavior and I'd rather `wash build` prepare an optimized binary by default. 

### Additional context

For those looking to contribute, here's where you may want to look for making these changes:

To build components: https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-lib/src/build/component.rs#L187

To build providers: https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-lib/src/build/provider.rs#L108
