### ISSUE TITLE
[BUG] Tracing : Additional serve-handle span appears in tracing while using http-server with http-client provider.

### ISSUE THREAD

**Issue by ritesh089** [wasmCloud/wasmCloud#2412]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

when i test the http-client-tiny-go example, or any components that receives a request from a http server capability provider and then calls a http endpoint, the tracing is not accurate.
The span after http-server's handle is serve-handle . it shows that serve handle takes longer than the http-server capability provider itself.

### Steps to reproduce

1) Enable tracing in wasmcloud host
2) Run this example 
3) Use a docker-compose with the below config:
```
version: "3"
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.58
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
```

4) test the component
```
curl localhost:8080
```

5) Observe the traces .

### Expected behavior

wasmcloud traces should be accurate and show the exact time it took to execute a certain code .

### Environment

- OS: MacOS
- Shell:zsh
- wasmcloud Version : 0.29.2

### Screenshots / Logs / Additional context

<img width="1774" alt="Screenshot 2024-06-28 at 10 04 04 AM" src="https://github.com/wasmCloud/wasmCloud/assets/25164825/a3d8df0b-b227-4cad-a088-c924fc4ba246">
