### ISSUE TITLE
Consolidate wasmCloud operator helm charts for simple, guided deploys (wasmCloud all-in-one helm chart)

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2550]
During the [wasmCloud Q3 roadmap planning session](https://wasmcloud.com/community/2024/07/02/community-meeting), we agreed that it would be great to have an all-in-one helm chart for the wasmCloud operator, NATS, wasmCloud, and Wadm for the simplest deployment onto Kubernetes. Other than combining these into a single, possibly streamlined, `values.yaml` and a chart that originates in this repo, I'm not sure if there's much more to say here.

_Ideally_, what I would love to be able to do is something like:
```
kind create cluster
helm install wasmcloud -f values.yaml --version 0.1.0 oci://ghcr.io/wasmcloud/charts/wasmcloud-operator
```

**Comment by ossfellow** [comment]
@brooksmtownsend, @joonas,  I decided to post the draft of the `Chart.yaml` file that I have in mind for this improved Helm chart to provide a more concise context to our conversation about _what this should be_ and _where it should be hosted_.
```yaml
apiVersion: v2
name: wasmcloud-operator
description: wasmCloud Operator harnesses the power of Kubernetes CRDs, to manage the lifecycle of wasmCloud Hosts, and provide a seamless experience for running WebAssembly applications on Kubernetes.
version: 1.0.0

type: application
appVersion: "1.0.0"

kubeVersion: ">=1.29.0"

dependencies:
  - name: nats
    repository: https://nats-io.github.io/k8s/helm/charts/nats
    condition: nats.enabled
    tags:
      - nats-server
    version: 1.x.x
  - name: wadm
    repository: oci://ghcr.io/wasmcloud/charts/wadm
    condition: wadm.enabled
    tags:
      - wadm
    version: 0.x.x

maintainers:
  - name: wasmCloud Maintainers
    email: maintainers@wasmcloud.com
    url: https://github.com/wasmCloud

home: https://github.com/wasmCloud/wasmcloud-operator
icon: https://github.com/wasmCloud/wasmCloud/blob/main/brand/icon/green/wasmCloud.icon-green.svg
sources:
  - https://github.com/wasmCloud/wasmCloud
  - https://github.com/wasmCloud/wadm
  - https://github.com/nats-io/nats-server

deprecated: false

keywords:
  - wasmcloud
  - wasi
  - webassembly
  - wadm
  - nats
  - cncf

annotations:
  license: Apache-2.0
``` 
I don't think this should be a new chart, but just an enhancement to the current wasmcloud-perator chart (i.e. v1.0.0); all it takes for a user of the existing chart to continue as is, is to **_disable_** the identified dependencies (which could be the default if we're insistent on minimizing impact).
That's why I think https://github.com/wasmCloud/wasmcloud-operator should be the chart's home, otherwise, we're going to confuse users about what's what, and why wasmCloud charts are scattered around.

I also intend to add documentation to the chart.
