### ISSUE TITLE
Installation Instructions: wasmcloud-wasmcloud-1 fails to start

### ISSUE THREAD

**Issue by rdifrango** [wasmCloud/wasmCloud#259]
I was following the installation instructions and the sample docker-compose file and `wasmcloud-wasmcloud-1` fails to start with the following error:

```
wasmcloud-wasmcloud-1  | /opt/app/releases/0.54.5/wasmcloud_host.sh: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/app/releases/0.54.5/wasmcloud_host.sh)
wasmcloud-wasmcloud-1  | Unusable Erlang runtime system! This is likely due to being compiled for another system than the host is running
wasmcloud-wasmcloud-1 exited with code 1
```

I did have to change the port for the `registry` as there's a system service that I can't remove running on `5000` but I assumed that should be fine.

Here's the compose file:

```
 This docker-compose file loads
#   nats with JetStream enabled
#   a local OCI registry
#   redis (for the kvredis capability provider)
#   wasmcloud_host

version: "3"
services:
  nats:
    image: fcr-nonprod.fmr.com/nats:2.7.2-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: [ "-js" ]
  redis:
    image: fcr-nonprod.fmr.com/redis:6.2
    ports:
      - "6379:6379"
  registry:
    image: fcr-nonprod.fmr.com/registry:2.7
    ports:
      - "5001:5001"
  wasmcloud:
    image: fcr-nonprod.fmr.com/wasmcloud/wasmcloud_host:latest
    environment:
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_PROV_RPC_HOST: nats
    ports:
      - "4000:4000"
      - "8080-8089:8080-8089" # Allows exposing examples on ports 8080-8089
```
