### ISSUE TITLE
[BUG] Trace is not using OTEL_EXPORTER_OTLP_TRACES_ENDPOINT env variable even though it set

### ISSUE THREAD

**Issue by saikiran1043** [wasmCloud/wasmCloud#2839]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I am setting the environment variable `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` to  send traces to my custom endpoint but it seems wasmcloud is still trying to send to default http://localhost:4318/v1/traces) .

Followed this doc : https://wasmcloud.com/docs/deployment/observability/tracing

### Steps to reproduce

I have used the following environment variables to setup traces using otel and export it to my end point (instead of default http://localhost:4318/v1/traces) .

```
export WASMCLOUD_TRACES_ENABLED="true"
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://myendpoint.com/ot/v1/traces
wash up
```

I have a wasm component with wadm file as below
```
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/http_client_tinygo_s.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: myhost.com/ghcr-io-proxy/ghcr.io/wasmcloud/http-server:0.21.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080

    - name: httpclient
      type: capability
      properties:
        image: myhost.com/ghcr-io-proxy/ghcr.io/wasmcloud/http-client:0.11.0 
```

I did `wash build` and `wash app deploy wadm.yaml`

The app is started and I am able hit the `curl http://localhost:8080` and see the result.

I expect traces to be sent to my endpoint, but in the terminal I see below error message where it is still trying to send to localhost

```
OpenTelemetry trace error occurred. error sending request for url (http://localhost:4318/v1/traces): error trying to connect: tcp connect error: Connection refused (os error 61)
```

Other Options tried:
I saw this code and thought I can send `wash up --override-traces-endpoint=<myendpoint>`, but seems `wash up` cli command doesn't support that.
https://github.com/wasmCloud/wasmCloud/blob/d92af18f183ba36e3794d4983905a7437ff2efce/src/main.rs#L259-L261

### Expected behavior

I expect traces to be sent to my endpoint, but in the terminal I see below error message where it is still trying to send to localhost

```
OpenTelemetry trace error occurred. error sending request for url (http://localhost:4318/v1/traces): error trying to connect: tcp connect error: Connection refused (os error 61)
```

### Environment

- OS: MacOS
- Shell: zsh
- wash version: 0.29.2
