### ISSUE TITLE
[FEATURE] Refactor example wadm manifests to reflect the new source/target structure

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2862]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Our current wadm manifests use a deprecated manifest format for wadm. For example, in [http-blobstore]():

```yaml
  components:
    - name: http-blobstore
      type: component
      properties:
        image: ghcr.io/wasmcloud/components/http-blobstore-rust:0.2.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: blobstore-fs
            namespace: wasi
            package: blobstore
            interfaces: [blobstore]
# deprecated
            target_config:
              - name: root-directory
                properties:
                  root: '/tmp'

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: link
          properties:
            target: http-blobstore
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
# deprecated
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
```

### Describe the solution you'd like

Instead of the old `source_config` and `target_config` blocks, we should consolidate examples to use the `source` and `target` blocks. So the above example should be changed to:

```yaml
  components:
    - name: http-blobstore
      type: component
      properties:
        image: ghcr.io/wasmcloud/components/http-blobstore-rust:0.2.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            namespace: wasi
            package: blobstore
            interfaces: [blobstore]
            target:
              name: blobstore-fs
              config:
                - name: root-directory
                  properties:
                    root: '/tmp'

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: link
          properties:
            target: 
              name: http-blobstore
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 127.0.0.1:8080
```

### Describe alternatives you've considered

wadm currently transforms this manifest automatically when you run `wash app put`, so we don't technically need to update this right now. However, it will be removed in the future so now is a good time.

### Additional context

Refer to the [Links section in the wadm 0.13.0 README for more information](https://github.com/wasmCloud/wadm/releases/tag/v0.13.0#Links)
