### ISSUE TITLE
[FEATURE] Add shared configs between components / capability

### ISSUE THREAD

**Issue by jamesstocktonj1** [wasmCloud/wasmCloud#2888]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I would like the ability to be able to share configurations between many components and/or capabilities. This can be useful for a range of situations such as having vaguely related services which need to be configured with the same parameters. One such example could be when you have an event producer and an event consumer that need to be configured to communicate on the same topic.

### Describe the solution you'd like

One solution could be a new `config` type as seen in this example config:
```
spec:
  components:
    - name: my-global-config
      type: config
      properties:
        topic: my-topic

    - name: producer
      type: component
      properties:
        image: ghcr.io/username/my-producer:0.1.0
        config:
          - name: my-global-config

    - name: consumer
      type: component
      properties:
        image: ghcr.io/username/my-consumer:0.1.0
        config:
          - name: my-global-config
```
By adding `- name: my-global-config` to the component config this allows both of the components to be configured with the value `topic: my-topic`.

### Describe alternatives you've considered

With this solution we could also allow a kind of "overriding" of config values such as the following:
```
spec:
  components:
    - name: my-global-config
      type: config
      properties:
        foo: bar

    - name: component-a
      type: component
      properties:
        image: ghcr.io/username/my-component-a:0.1.0
        config:
          - name: my-global-config
      # resultant config:
      #   - foo: bar

    - name: component-b
      type: component
      properties:
        image: ghcr.io/username/my-component-b:0.1.0
        config:
          - name: my-global-config
            properties:
              foo: bat
      # resultant config:
      #   - foo: bat
```
This could be a possible solution to avoid overwriting the `my-global-config` on deployment. But this may make things complicated when it comes to subscribing to config changes.
