### ISSUE TITLE
[BUG] `wash dev` loops indefinitely into restarting Rust-based component after first change

### ISSUE THREAD

**Issue by atifsyedali** [wasmCloud/wasmCloud#3180]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

`wash dev` loops indefinitely into restarting Rust-based component after first change. I don't think it is working.

### Steps to reproduce

1. Create a new Rust component template
2. `wash dev`
3. Make a change in your component
4. Watch the console restart your component indefinitely on a loop

```
 restarting component @ [/opt/xxx/hello-rust/build/http_hello_world_s.wasm]...
👀 watching for file changes (press Ctrl+c to stop)...
    Finished `release` profile [optimized] target(s) in 0.07s
 restarting component @ [/opt/xxx/hello-rust/build/http_hello_world_s.wasm]...
👀 watching for file changes (press Ctrl+c to stop)...
    Finished `release` profile [optimized] target(s) in 0.07s
 restarting component @ [/opt/xxx/hello-rust/build/http_hello_world_s.wasm]...
👀 watching for file changes (press Ctrl+c to stop)...
    Finished `release` profile [optimized] target(s) in 0.07s
 restarting component @ [/opt/xxx/hello-rust/build/http_hello_world_s.wasm]...
👀 watching for file changes (press Ctrl+c to stop)...
    Finished `release` profile [optimized] target(s) in 0.07s
 restarting component @ [/opt/xxx/hello-rust/build/http_hello_world_s.wasm]...
```

### Expected behavior

Restarts once and everything is loaded again.

### Environment

- OS: Linux
- Shell: bash
- wasmcloud Version [e.g. 1.2.0]

**Comment by vados-cosmonic** [comment]
Hey @atifsyedali thanks for reporting this -- would you mind including a few things? I'd like to look into this ASAP!

- your `wash` version (if you run `wash --version` you should get versions for most things)
- Are you using `hello-world-rust` with any considerable modifications? Or did you basically `wash new`?

Anything else that would help reproduce would be great!

**Comment by lachieh** [comment]
This _might_ get fixed with #3140, specifically the part about ignoring generated files

**Comment by atifsyedali** [comment]
```
wash          v0.32.0
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.0
```

I just followed the docs to create a new component in Rust -- yes hello-world example.

**Comment by vados-cosmonic** [comment]
Hey @atifsyedali would you mind updating your `wash` instance `wash` `34.1` -- you're actually using the *old* version of `wash dev`!

The new `wash dev` works quite differently, and has some more smarts around automatically fulfilling requirements, it *does not* not infinite loop for an [example like `http-hello-world` (AKA "hello-world-rust" in `wash new component`)](https://github.com/wasmCloud/wasmCloud/tree/main/examples/rust/components/http-hello-world), I've tested that personally (which is why I asked what version you were using, as sweat rolled down my brow :sweat_smile: ).

Anything after [version `0.34.0`](https://github.com/wasmCloud/wasmCloud/issues/2508#issuecomment-2367897072) will have the new `wash dev` ("v2"), and should work.

Note that in the past if you had to do extra set up like starting providers, with the new `wash dev` you *should not* need to -- ex. a basic HTTP server provider should be spun up for you.

**Comment by vados-cosmonic** [comment]
Oh and @lachieh IIRC current wash dev shouldn't infinite loop even with `target`/generated folders changing, that fix improved experience but it wasn't to stop an infinite loop -- it just gets rid of some extra reloads early!

**Comment by atifsyedali** [comment]
Sorry my bad -- vscode devcontainer cache.

However, I have a new error now:

```
$ wash dev
 Resolved wash session ID [4XlFej]
 Starting a new host...
👀 Found wadm version on the disk: wadm-cli 0.14.0
✅ Using wadm version [v0.14.0]
 Successfully started wasmCloud instance
 Successfully started host, logs writing to /home/ubuntu/.wash/dev/4XlFej/wasmcloud.log
 Building project...
    Finished `release` profile [optimized] target(s) in 0.06s
✅ successfully built project at [/xxx/hello-rust/build/http_hello_world_s.wasm]
Detected component dependencies: ["keyvalue-nats", "keyvalue-nats", "custom-wasmcloud-example", "http-server"]
 Failed to run first dev loop iteration, will retry: failed to generate a WADM manifest from (session [4XlFej])
👀 watching for file changes (press Ctrl+c to stop)...
 Building project...
    Finished `release` profile [optimized] target(s) in 0.06s
✅ successfully built project at [/xxx/hello-rust/build/http_hello_world_s.wasm]
Detected component dependencies: ["keyvalue-nats", "keyvalue-nats", "custom-wasmcloud-example", "http-server"]

failed to run dev loop iteration

Caused by:
    0: failed to generate a WADM manifest from (session [4XlFej])
    1: failed to generate component
    2: failed to generate properties for component
    3: missing image ref for generated provider dependency [custom-wasmcloud-example]
```

My wash --version

```
wash          v0.34.1
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.1
```

Doing a separate `wash build` then a `wash app deploy` works. I don't have any issue in my wadm.yaml, which is given below:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-hello-world
  annotations:
    description: 'HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)'
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/source-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/http-hello-world/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/http-hello-world/README.md
    wasmcloud.dev/homepage: https://github.com/wasmCloud/wasmCloud/tree/main/examples/rust/components/http-hello-world
    wasmcloud.dev/categories: |
      http,http-server,rust,hello-world,example
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/http_hello_world_s.wasm
        # To use the a precompiled version of this component, use the line below instead:
        # image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            instances: 1

        - type: link
          properties:
            target: hostname-provider
            namespace: wasmcloud
            package: example
            interfaces: [system-info]
        
        - type: link
          properties:
            target: kvredis
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target_config:
              - name: redis-url
                properties:
                  url: redis://:passw@redis:6379

    # Add a capability provider that allows for key-value storage
    - name: kvredis
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.27.0

    - name: hostname-provider
      id: hostname-provider
      type: capability
      properties:
        image: file:///xxx/hostname-provider-rust/build/wasmcloud-provider-custom-template.par.gz
      traits:
        - type: link
          properties:
            target: http-component
            namespace: wasmcloud
            package: example
            interfaces: [process-data]
      config:
        - name: provider-config
          properties:
            foo: bar

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.1
        ## To configure OTEL integration for this provider specifically, uncomment the lines below
        # config:
        #   - name: otel
        #     properties:
        #       otel_exporter_otlp_endpoint: "http://all-in-one:4318"
        #       otel_exporter_otlp_traces_endpoint: "http://traces-backend/v1/traces"
        #       otel_exporter_otlp_metrics_endpoint: "http://metrics-backend/v1/metrics"
        #       otel_exporter_otlp_logs_endpoint: "http://logs-backend/v1/logs"
      traits:
        # Establish a unidirectional link from this http server provider (the "source")
        # to the `http-component` component (the "target") so the component can handle incoming HTTP requests,
        #
        # The source (this provider) is configured such that the HTTP server listens on 127.0.0.1:8080
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
```

Wash version:
```
