### ISSUE TITLE
[BUG] Provider -> Component calls not working when 2 providers link to 1 component

### ISSUE THREAD

**Issue by atifsyedali** [wasmCloud/wasmCloud#3285]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

It seems that, when two providers that link to the same component, one provider will not be able to communicate with the component.

### Steps to reproduce

The following is a minimal example by following the new provider template. To summarize, it creates a new provider from the rust provider template, adds an HTTP server to point to the test component generated, and in the HTTP handler implementation of the test component, it makes a call to `call()` on the provider. The `call()` on the provider is already implemented such that it iterates through the list of link_to components and calls `process_data` on all of them. So the end result is, once you deploy this app, you `curl localhost:8082` and it should give you back something. But it hangs.

Steps to reproduce:
1. Start with a new provider `wash new provider test-provider --template-name custom-template-rust`
2. Edit `test-provider/wadm.yaml` and add an HTTP server provider like given below.
3. Edit `test-provider/component/src/lib.rs` and add the HTTP trait like given below.
4. Edit `test-provider/component/wit/world.wit` and add the HTTP incoming handler like below. 
5. Edit `test-provider/component/wit/deps.toml` and edit it like given below.
6. Inside the `test-provider/component` folder, run `wit-deps update`. 
7. Inside the `test-provider/component` folder, run `wash build`.
8. Inside the `test-provider` folder, run `wash build`.
9. Run `wash up` in another terminal.
10. Inside the `test-provider` folder, run `wash app deploy wadm.yaml --replace`.

----

`wadm.yaml`:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: custom-template-provider
  annotations:
    version: v0.0.1
    description: 'An application with a provider and component built for extending wasmCloud with custom capabilities'
spec:
  components:
    - name: test-component
      type: component
      properties:
        image: file://./component/build/custom_template_test_component.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        # Link the component to the provider on wasmcloud:example/system-info
        - type: link
          properties:
            target: custom-template
            namespace: wasmcloud
            package: example
            interfaces: [system-info]

    - name: custom-template
      type: capability
      properties:
        image: file://./build/wasmcloud-provider-custom-template.par.gz
        id: custom-template
        config:
          - name: provider-config
            properties:
              foo: bar
      traits:
        # Link the provider to the component on wasmcloud:example/process-data
        - type: link
          properties:
            target: test-component
            namespace: wasmcloud
            package: example
            interfaces: [process-data]

        # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.1
      traits:
        # Establish a unidirectional link from this http server provider (the "source")
        # to the `http-component` component (the "target") so the component can handle incoming HTTP requests,
        #
        # The source (this provider) is configured such that the HTTP server listens on 127.0.0.1:8080
        - type: link
          properties:
            target: test-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8082
```

----

`test-provider/component/src/lib.rs`:
```
wit_bindgen::generate!({ generate_all });

use crate::exports::wasi::http::incoming_handler;
use crate::exports::wasmcloud::example::process_data;
use crate::wasi::logging::logging::*;
use crate::wasmcloud::example::system_info::Kind;
use crate::wasi::http::types::*;

struct CustomTemplateComponent;


impl incoming_handler::Guest for CustomTemplateComponent {
    fn handle(request: IncomingRequest, response_out: ResponseOutparam) {
        let response = OutgoingResponse::new(Fields::new());
        response.set_status_code(200).unwrap();
        let response_body = response.body().unwrap();

        wasi::logging::logging::log(
            wasi::logging::logging::Level::Info,
            "",
            format!("About to make a call").as_str(),
        );

        let call_result = wasmcloud::example::system_info::call();

        wasi::logging::logging::log(
            wasi::logging::logging::Level::Info,
            "",
            format!("Received from .call...{call_result}").as_str(),
        );

        response_body
            .write()
            .unwrap_or_else(|err| {
                wasi::logging::logging::log(
                    wasi::logging::logging::Level::Error,
                    "",
                    &format!("There was an error while trying to write response"),
                );
                panic!("oops")
            })
            .blocking_write_and_flush(format!("The result was {call_result}").as_bytes())
            .unwrap_or_else(|err| {
                wasi::logging::logging::log(
                    wasi::logging::logging::Level::Error,
                    "",
                    &format!("There was an error while trying to write and flush response"),
                );
                panic!("oops")
            });

        OutgoingBody::finish(response_body, None).expect("failed to finish response body");
        ResponseOutparam::set(response_out, Ok(response));
    }
}

impl process_data::Guest for CustomTemplateComponent {
    fn process(data: process_data::Data) -> String {
        log(Level::Info, "", &format!("Data received: {:?}", data));
        // Request OS and architecture information
        let os = crate::wasmcloud::example::system_info::request_info(Kind::Os);
        let arch = crate::wasmcloud::example::system_info::request_info(Kind::Arch);
        format!("Provider is running on {os}-{arch}").to_string()
    }
}

export!(CustomTemplateComponent);
```

----

`test-provider/component/wit/world.wit`:
```
package wasmcloud:custom;

world component {
  // Import logging for processing data
  import wasi:logging/logging;

  // Notice here the component has the inverse direction for importing/exporting interfaces
  // compared to the provider. This allows us to compose the component with the provider, each
  // import linking up to an export.
  import wasmcloud:example/system-info;
  export wasmcloud:example/process-data;
  export wasi:http/incoming-handler@0.2.0;
}
```

----

`test-provider/component/wit/deps.toml`
```
custom = "../../wit"
http = "https://github.com/WebAssembly/wasi-http/archive/v0.2.0.tar.gz"
logging = "https://github.com/WebAssembly/wasi-logging/archive/main.tar.gz"
```

### Expected behavior

The above simple case should have worked.

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]
