### ISSUE TITLE
[BUG] Config changed receiver errored

### ISSUE THREAD

**Issue by duffney** [wasmCloud/wasmCloud#3329]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

An application deployment loops through failure and reconciliation when deployed to wasmCloud.

### Steps to reproduce

1. Deploy wasmcloud to Kubernetes (AKS cluster) following the [docs](https://wasmcloud.com/docs/deployment/k8s/).
2. Run `kubectl apply -f deploy.yaml`

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-wasi-hello
spec:
  components:
    - name: rust-wasi-hello
      type: component
      properties:
        # image: ghcr.io/yoshuawuyts/rust-wasi-hello:latest
        image: ghcr.io/ricochet/rust-wasi-hello:v0.1.0
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        # Establish a unidirectional link from this http server provider (the "source")
        # to the `http-component` component (the "target") so the component can handle incoming HTTP requests,
        #
        # The source (this provider) is configured such that the HTTP server listens on 127.0.0.1:8080
        - type: link
          properties:
            target: rust-wasi-hello
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8080
```

### Expected behavior

Expected the application deployment to be successful and be able to forward ports to access the web application.

### Environment

- OS: [Linux]
- Shell [zsh]
- wasmcloud Version [1.2.1]

### Screenshots / Logs / Additional context

wasmCloud-host logs:

```
k logs -c wasmcloud-host wasmcloud-host-c586cb98b-8mzvn
{"timestamp":"2024-10-15T15:18:59.163022Z","level":"INFO","fields":{"message":"event: connected"},"target":"async_nats_wrpc"}
{"timestamp":"2024-10-15T15:18:59.163594Z","level":"INFO","fields":{"message":"event: connected"},"target":"async_nats_wrpc"}
{"timestamp":"2024-10-15T15:18:59.170385Z","level":"INFO","fields":{"message":"created bucket with 1 replica","bucket":"LATTICEDATA_default"},"target":"wasmcloud_host::wasmbus"}
{"timestamp":"2024-10-15T15:18:59.172936Z","level":"INFO","fields":{"message":"created bucket with 1 replica","bucket":"CONFIGDATA_default"},"target":"wasmcloud_host::wasmbus"}
{"timestamp":"2024-10-15T15:18:59.178445Z","level":"INFO","fields":{"message":"wasmCloud host started","host_id":"NCAXICLMI5ZZQIIBAI4KI2RE7AYH4HFUZA7CWX6CCNJNXV2M2DMJTEFR"},"target":"wasmcloud_host::wasmbus"}
{"timestamp":"2024-10-15T15:20:03.189809Z","level":"INFO","fields":{"message":"handling start provider","provider_ref":"ghcr.io/wasmcloud/http-server:0.22.0","provider_id":"rust_wasi_hello-httpserver"},"target":"wasmcloud_host::wasmbus"}
{"timestamp":"2024-10-15T15:20:04.702936Z","level":"INFO","fields":{"message":"provider started","provider_ref":"ghcr.io/wasmcloud/http-server:0.22.0","provider_id":"rust_wasi_hello-httpserver"},"target":"wasmcloud_host::wasmbus"}
{"timestamp":"2024-10-15T15:20:04.703219Z","level":"ERROR","fields":{"message":"Config changed receiver errored, this means that the config sender has dropped and the whole bundle has failed","error":"channel closed"},"target":"wasmcloud_host::wasmbus::config"}
{"timestamp":"2024-10-15T15:20:04.716333Z","level":"INFO","fields":{"message":"Starting capability provider rust_wasi_hello-httpserver instance f95b65be-132f-48b4-bfe6-469281cec565 with nats url nats://127.0.0.1:4222"},"target":"wasmcloud_provider_sdk::provider","span":{"name":"http-server-provider","name":"init_provider"},"spans":[{"name":"http-server-provider","name":"init_provider"}]}
{"timestamp":"2024-10-15T15:20:04.718061Z","level":"INFO","fields":{"message":"event: connected"},"target":"async_nats_wrpc"}
{"timestamp":"2024-10-15T15:20:04.718077Z","level":"INFO","fields":{"message":"nats client connected"},"target":"wasmcloud_provider_sdk"}
{"timestamp":"2024-10-15T15:20:09.717304Z","level":"INFO","fields":{"message":"Linking component with provider"},"target":"wasmcloud_provider_sdk::provider"}
{"timestamp":"2024-10-15T15:20:09.717421Z","level":"INFO","fields":{"message":"httpserver starting listener for target","addr":"0.0.0.0:8080","target":"rust_wasi_hello-rust_wasi_hello"},"target":"wasmcloud_provider_http_server","span":{"settings":"ServiceSettings { address: Some(0.0.0.0:8080), tls: Tls { cert_file: None, priv_key_file: None }, cors: Cors { allowed_origins: Some(AllowedOrigins([])), allowed_headers: Some(AllowedHeaders([\"accept\", \"accept-language\", \"content-type\", \"content-language\"])), allowed_methods: Some(AllowedMethods([\"GET\", \"POST\", \"PUT\", \"DELETE\", \"HEAD\", \"OPTIONS\"])), exposed_headers: Some(ExposedHeaders([])), max_age_secs: Some(300) }, log: Log { log_level: None }, timeout_ms: None, cache_control: None, readonly_mode: Some(false), max_content_len: Some(\"104857600\"), extra: {} }","target":"rust_wasi_hello-rust_wasi_hello","name":"new"},"spans":[{"settings":"ServiceSettings { address: Some(0.0.0.0:8080), tls: Tls { cert_file: None, priv_key_file: None }, cors: Cors { allowed_origins: Some(AllowedOrigins([])), allowed_headers: Some(AllowedHeaders([\"accept\", \"accept-language\", \"content-type\", \"content-language\"])), allowed_methods: Some(AllowedMethods([\"GET\", \"POST\", \"PUT\", \"DELETE\", \"HEAD\", \"OPTIONS\"])), exposed_headers: Some(ExposedHeaders([])), max_age_secs: Some(300) }, log: Log { log_level: None }, timeout_ms: None, cache_control: None, readonly_mode: Some(false), max_content_len: Some(\"104857600\"), extra: {} }","target":"rust_wasi_hello-rust_wasi_hello","name":"new"}]}
```
