### ISSUE TITLE
[BUG] Wasmcloud fails to build registry config

### ISSUE THREAD

**Issue by hardliner66** [wasmCloud/wasmCloud#3366]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The wasmcloud docker container keeps restarting because there's something wrong with the registry config.

### Steps to reproduce

Start the docker compose file and check the logs.

docker-compose.yml
```yaml
# This docker-compose file starts an entire wasmCloud ecosystem, including:
#   a NATS server
#   a local OCI registry
#   grafana + prometheus + tempo for metrics and tracing
#   a wasmCloud host
#   a WADM server for managing applications

services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: ["-js"]
    restart: always

  registry:
    image: registry:2.8
    ports:
      - "5000:5000"
    restart: always

  grafana:
    image: grafana/grafana:10.0.10
    ports:
      - 5050:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
      - tempo
    restart: always

  otelcol:
    depends_on:
      - prometheus
      - tempo
    image: otel/opentelemetry-collector-contrib:0.93.0
    ports:
      - 4317:4317
      - 4318:4318
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml
    restart: always

  prometheus:
    image: prom/prometheus:v2.49.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  tempo:
    image: grafana/tempo:2.3.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 4318 # This port is used for sending traces from otel-collector to tempo
      - 7999:7999 # tempo
    restart: always

  wasmcloud:
    depends_on:
      - "nats"
      - "otelcol"
      - "registry"
    image: wasmcloud/wasmcloud:latest
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_distribution=info,cranelift_codegen=warn
      WASMCLOUD_LOG_LEVEL: debug
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_ALLOW_FILE_LOAD: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: registry:5000
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
    ports:
      - "8000-8100:8000-8100" # Expose ports 8000-8100 for examples that use an HTTP server
    restart: always

  wadm:
    depends_on:
      - "nats"
    image: ghcr.io/wasmcloud/wadm:latest
    environment:
      - WADM_NATS_SERVER=nats
    restart: always
```

### Expected behavior

The docker container should start properly

### Environment

- OS: Windows
- Shell: Powershell
- wasmcloud Version: Latest

### Screenshots / Logs / Additional context

wasmcloud-1 exited with code 101
wasmcloud-1   | 2024-10-18T10:22:28.496367Z DEBUG new: wasmcloud_host::wasmbus: connecting to NATS control server ctl_nats_url="nats://nats:4222"
wasmcloud-1   | 2024-10-18T10:22:28.496453Z DEBUG new: wasmcloud_host::wasmbus: connecting to NATS RPC server rpc_nats_url="nats://nats:4222"
wasmcloud-1   | 2024-10-18T10:22:28.499203Z  INFO async_nats: event: connected
wasmcloud-1   | 2024-10-18T10:22:28.499526Z  INFO async_nats: event: connected
wasmcloud-1   | 2024-10-18T10:22:28.509776Z  INFO new:create_bucket: wasmcloud_host::wasmbus: bucket already exists. Skipping creation. bucket=LATTICEDATA_default
wasmcloud-1   | 2024-10-18T10:22:28.510224Z  INFO new:create_bucket: wasmcloud_host::wasmbus: bucket already exists. Skipping creation. bucket=CONFIGDATA_default
wasmcloud-1   | 2024-10-18T10:22:28.510267Z DEBUG new:merge_registry_config: wasmcloud_host::wasmbus: set allowed_insecure oci_registry_url=registry:5000
wasmcloud-1   | thread 'main' panicked at /build/source/crates/host/src/wasmbus/mod.rs:654:26:
wasmcloud-1   | failed to build registry config: missing reg auth
wasmcloud-1   | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
canceled
