### ISSUE TITLE
[FEATURE] Support link config and secrets for interface overrides in wash dev

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#3522]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

When overriding an interface for wash dev, I can supply configuration and secrets for that specific overridden component but not configuration/secrets to pass on the link to/from that component.

### Describe the solution you'd like

In my wasmCloud.toml, in addition to the following configuration:
```toml
[[dev.overrides.imports]] 
interface_spec = "wasi:keyvalue/*@0.2.0-draft"
image_ref = "ghcr.io/wasmcloud/keyvalue-redis:0.28.1"
config = { values = { url="redis://127.0.0.1:6379" } }
```

I should be able to put configuration on the link instead of the provider, e.g.
```toml
[[dev.overrides.imports]] 
interface_spec = "wasi:keyvalue/*@0.2.0-draft"
image_ref = "ghcr.io/wasmcloud/keyvalue-redis:0.28.1"
link_config = { values = { url="redis://127.0.0.1:6379" } }
```

### Describe alternatives you've considered

N/A
