### ISSUE TITLE
[RFC] Provenance and Attestation in wasmCloud: Foundation and Future Direction

### ISSUE THREAD

**Issue by ossfellow** [wasmCloud/wasmCloud#3787]
### RFC Title

Provenance and Attestation in wasmCloud: Foundation and Future

### Introduction

Software supply chain security has become increasingly critical as organizations face sophisticated attacks targeting development and distribution pipelines. Major incidents like the SolarWinds attack in 2020 and the Log4Shell vulnerability in 2021 have highlighted the urgent need for better supply chain security practices. The Log4j incident, in particular, demonstrated how Software Bills of Materials (SBOMs) can be crucial in rapidly identifying and remediation of vulnerabilities in the software supply chain.

The Linux Foundation, through initiatives like the Open Source Security Foundation (OpenSSF) and the SLSA (Supply chain Levels for Software Artifacts) framework, has been leading efforts to establish industry standards for supply chain security. These initiatives emphasize provenance and attestation as fundamental security mechanisms that help protect against supply chain threats. Provenance provides verifiable records of where and how software artifacts were produced, while attestation offers cryptographic proof of their integrity and characteristics.

These mechanisms are essential for:

- Verifying the authenticity of software artifacts
- Detecting tampering during build and distribution
- Establishing chain of custody from source to deployment
- Meeting compliance requirements for software delivery
- Enabling users to make informed trust decisions

### Motivation

For the wasmCloud platform, implementing provenance and attestation through signed Software Bills of Materials (SBOMs) provides several key benefits:

- Enables users to verify the authenticity of wasmCloud binaries, built-in providers, and example components
- Demonstrates supply chain security best practices for the wider WebAssembly ecosystem
- Supports organizations with strict security requirements in adopting wasmCloud
- Provides transparency into the platform's dependencies and build process
- Facilitates automated security scanning and vulnerability management
- Establishes foundation for enterprise-grade security integration through standardized identity and trust frameworks

### Detailed Design

This RFC addresses both immediate supply chain security needs and future trust architecture considerations:

1. Immediate Implementation (Phase 1):
   - Generate and sign SBOMs and attestations for all wasmCloud artifacts:
     - Binary artifacts (wasmCloud runtime, wash CLI)
     - OCI images (including both Debian and Wolfi-based variants)
   - Make these verifiable artifacts available through:
     - GitHub releases (for binaries and their SBOMs)
     - Container registries (for OCI images with embedded SBOMs)

2. Future Integration Paths (Phase 2 & 3):
   - Optional tooling integration through wash plugins
   - Native verification capabilities in Rust
   - Integration possibilities with SPIFFE/SPIRE for:
     - External root of trust
     - Workload identity verification
     - Enterprise grade security integration

### Phase 1: Generation of SBOMs and Attestations

To achieve [SLSA v1 Build Level 3](https://slsa.dev/spec/v1.0/levels), using the [in-toto](https://github.com/in-toto/attestation/tree/main/spec/v1) format, two reusable GitHub workflows will be introduced:

1. A workflow for generating SBOMs and attestations for binary artifacts:

```yaml
# Reusable workflow for generating SBOMs and attestations for binary artifacts
# This workflow is designed to be called from release jobs to create
# verifiable provenance for wasmCloud binaries
name: Create Binary SBOM and Provenance

on:
  workflow_call:
    inputs:
      artifact-path:
        description: "Path to the binary artifact"
        required: true
        type: string
      artifact-name:
        description: "Name of the artifact"
        required: true
        type: string

# Required permissions for SLSA attestation
permissions:
  contents: read
  id-token: write # Needed for Sigstore API to generate certificates
  attestations: write # Needed for pushing attestations

jobs:
  create-sboms-and-attestation:
    runs-on: ubuntu-22.04
    steps:
      # Generate Syft configuration dynamically to ensure proper version tagging
      - name: Setup Syft config
        run: |
          cat > .syft.yaml << EOF
          package:
            cataloger:
              enabled: true
              scope: "squashed"

          source:
            name: "wasmcloud"
            version: "${GITHUB_REF_NAME}"

          output:
            format: "spdx-json"
            file: "sbom.json"
          EOF

      # Generate SBOM in SPDX format using Syft
      - name: Create Binary SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ${{ inputs.artifact-path }}
          artifact-name: sbom-${{ inputs.artifact-name }}-spdx.json
          format: spdx-json
          config: .syft.yaml

      # Create and sign attestation using Sigstore's API through GitHub OIDC token
      - name: Create Binary Provenance
        uses: actions/attest-sbom@v1 # Uses Sigstore API for certificate generation
        with:
          subject-path: ${{ inputs.artifact-path }}
          sbom-path: sbom-${{ inputs.artifact-name }}-spdx.json
```

2. A workflow for generating SBOMs and attestations for OCI images:

```yaml
# Reusable workflow for generating SBOMs and attestations for OCI images
# This workflow handles container image specific requirements and attaches
# the SBOM directly to the image manifest
name: Create OCI SBOM and Provenance

on:
  workflow_call:
    inputs:
      image-ref:
        description: "Full reference to the OCI image"
        required: true
        type: string

# Required permissions for SLSA attestation
permissions:
  contents: read
  id-token: write # Needed for creating attestations
  attestations: write # Needed for pushing attestations

jobs:
  create-sboms-and-attestation:
    runs-on: ubuntu-22.04
    steps:
      # Generate Syft configuration with OCI-specific settings
      - name: Setup Syft config
        run: |
          cat > .syft.yaml << EOF
          package:
            cataloger:
              enabled: true
              scope: "squashed"  # Important for container images to handle layers correctly

          source:
            name: "wasmcloud"
            version: "${GITHUB_REF_NAME}"

          output:
            format: "spdx-json"
            file: "sbom.json"
          EOF

      # Generate SBOM for the container image
      - name: Create OCI SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ inputs.image-ref }}
          artifact-name: sbom-${{ inputs.image-ref }}-spdx.json
          format: spdx-json
          config: .syft.yaml

      # Attach SBOM to the image using Sigstore for signing
      - name: Attach SBOM to Image
        uses: anchore/sbom-action@v0 # Internally uses Sigstore API for signing
        with:
          image: ${{ inputs.image-ref }}
          artifact-name: sbom-${{ inputs.image-ref }}-spdx.json
          format: spdx-json
          config: .syft.yaml
          attach: true # Attaches signed SBOM to the image
```

The `smart-releases` job in `wasmcloud.yml` will be updated to use these workflows:

```yaml
# .github/workflows/wasmcloud.yml
smart-release:
  permissions:
    contents: write
    pull-requests: write
    id-token: write # Added for attestation
    attestations: write # Added for attestation

  steps:
    # Generate SBOMs and attestations only during release
    - name: Download Release Artifacts
      if: ${{ inputs.do-release }}
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Generate Binary SBOMs and Attestations
      if: ${{ inputs.do-release }}
      uses: ./.github/workflows/create-binary-attestation.yml
      with:
        artifact-path: ./artifacts/wasmcloud/bin
        artifact-name: ${{ inputs.crate }}

    - name: Generate OCI SBOMs and Attestations
      if: ${{ inputs.do-release }}
      uses: ./.github/workflows/create-oci-attestation.yml
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/wasmcloud:${{ inputs.crate }}

    # ... existing smart-release steps ...

    # Release with cargo smart-release and include SBOMs
    - name: release
      if: ${{ inputs.do-release }}
      env:
        GH_TOKEN: ${{ github.token }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
      run: |
        # Add SBOMs to the release assets directory
        mkdir -p .release-assets
        cp ./sbom-${{ inputs.crate }}-spdx.json .release-assets/
        cp ./sbom-${{ inputs.crate }}-oci-spdx.json .release-assets/

        # Run smart-release with assets
        cargo smart-release \
          --update-crates-index \
          --execute \
          --no-changelog-preview \
          --no-changelog \
          --assets=".release-assets/*" \
          ${{ inputs.additional-args }} \
          ${{ inputs.crate }}
```

Collectively, the workflows will:

1. Generate SBOMs for both binaries and OCI images
2. Create attestations using GitHub's OIDC token
3. Attach SBOMs to OCI images
4. Include binary SBOMs in GitHub releases

### Verifying Provenance and SBOMs

The easiest method for verifying provenance and SBOMs is using the [GitHub CLI](https://cli.github.com/). This method provides the following advantages:

- Simpler verification process
- Direct integration with GitHub's API
- Automatic handling of OIDC token verification
- Built-in support for both binary and OCI image attestations
- JSON output format for automated verification in CI/CD pipelines

#### For wasmCloud Binaries

```bash
# Install GitHub CLI if not already installed
brew install gh  # or your system's package manager

# Verify binary attestation directly
gh attestation verify wasmcloud-x86_64-unknown-linux-musl-v1.42.0 \
  --repo wasmCloud/wasmCloud \
  --predicate-type https://spdx.dev/Document

# For detailed verification results
gh attestation verify wash-x86_64-unknown-linux-musl-v0.37.0 \
  --repo wasmCloud/wasmCloud \
  --predicate-type https://spdx.dev/Document \
  --format json
```

#### For OCI Images

```bash
# Verify OCI image attestation
gh attestation verify oci://ghcr.io/wasmcloud/http-server:0.25.0 \
  --repo wasmCloud/wasmCloud \
  --predicate-type https://spdx.dev/Document \
  --bundle-from-oci

# View detailed verification results
gh attestation verify oci://ghcr.io/wasmcloud/keyvalue-redis:0.28.2 \
  --repo wasmCloud/wasmCloud \
  --predicate-type https://spdx.dev/Document \
  --bundle-from-oci \
  --format json
```

> For automated verification in CI/CD pipelines, the GitHub CLI approach with `--format json` output can be easily integrated into deployment workflows.

The GitHub CLI verifies attestations stored in GitHub's attestation API that were signed using Sigstore through GitHub's OIDC integration during the build process. For additional SBOM analysis and verification, users can leverage other industry-standard tools:

- [SPDX Tools](https://github.com/spdx/tools) - For validating SPDX format and license compliance
- [Syft](https://github.com/anchore/syft) - For SBOM generation and verification
- [Grype](https://github.com/anchore/grype) - For vulnerability scanning based on Syft-generated SBOMs
- [SBOM Scorecard](https://github.com/eBay/sbom-scorecard) - For SBOM quality assessment

### Phase 2: Integration with wasmCloud Tooling (Optional)

As a convenience method, a [wash plugin](https://wasmcloud.com/docs/ecosystem/wash/plugins) could be developed as a shim to the GitHub CLI to verify SBOMs and attestations. It could install the GitHub CLI if it's not present.

### Phase 3: Native Verification and Trust Architecture (Future Consideration)

As wasmCloud evolves, we need to consider both native verification capabilities, and how they integrate with broader trust architectures. While the Rust ecosystem for SLSA attestation is still maturing, we can explore:

- Native Verification Capabilities:
  - Developing Rust bindings for existing verification tools
  - Contributing to emerging Rust attestation projects
  - Creating wasmCloud-specific verification tools

- Trust Architecture Integration:
  - Defining trust boundaries and transitions
  - Supporting external root of trust systems
  - Enabling enterprise security integration patterns

While native verification capabilities are important, they alone cannot establish end-to-end trust for the wasmCloud platform. Even when `wash` and `wasmCloud host` binaries include _SBOM and attestation verification_ capabilities, enterprise-grade security requires the root of trust to remain external to these binaries, as allowing them to self-verify would create a circular trust dependency that undermines the entire security model.

This consideration of trust architecture naturally leads us to explore integration with established cloud-native security frameworks.

### External Trust and Platform Integration

The separation of verification tools from the root of trust opens interesting possibilities for integration with cloud-native security patterns, particularly CNCF's [SPIFFE (Secure Production Identity Framework for Everyone)](https://www.cncf.io/projects/spiffe/). SPIFFE provides a standardized way to securely identify software systems in dynamic and heterogeneous environments through:

- Cryptographically-verifiable identity documents (SVIDs)
- Automated workload attestation
- Dynamic identity provisioning
- Platform-agnostic trust domains

#### Integration Approaches

Two approaches merit consideration for integrating external trust with wasmCloud's security model:

1. Boundary Integration:
   - SPIFFE/SPIRE integration at platform edges:
     - `wash` and `wasmCloud host` binaries receive SVIDs
     - External workload verification via SPIRE
     - Internal verification continues using NATS nkeys

   Advantages:
   - Minimal changes to existing architecture
   - Clear separation of concerns
   - Immediate enterprise grade security integration
   - Preserves proven internal security model

   Challenges:
   - Limited to platform boundaries
   - Two separate identity systems to maintain
   - Potential complexity in trust transition points

2. Deep Integration:
   - Replace or augment NATS nkeys system with SPIFFE SVIDs:
     - All workloads use SPIFFE identities
     - Unified identity model throughout
     - Native SPIRE attestation for all components

   Advantages:
   - Consistent identity model
   - Enterprise grade security integration
   - Simplified trust architecture
   - Better alignment with cloud-native patterns

   Challenges:
   - Major architectural changes required
   - Migration complexity for existing deployments
   - Performance implications to evaluate
   - NATS integration considerations

Both approaches merit consideration, and the choice depends on specific deployment needs and security requirements. If there's community interest in pursuing either approach, a future RFC could be put forward to detail the design and implementation strategy.

### References

- [SLSA Provenance Specification](https://slsa.dev/provenance/v1)
- [Sigstore](https://sigstore.dev/)
- [Syft](https://github.com/anchore/syft)
- [GitHub CLI](https://cli.github.com/)
- [SPIFFE Concepts](https://spiffe.io/docs/latest/spiffe-about/spiffe-concepts/)

### Backwards Compatibility

The proposed changes maintain full backward compatibility:

Phase 1 (Current Scope):
- SBOM generation and attestation are additive features
- Existing build and release processes continue to function as before
- Verification is optional and doesn't affect existing deployments
- No changes to runtime behavior or APIs

Future Considerations:
- Phase 2 (wash plugin) would be entirely optional
- Phase 3 implications would be addressed in a separate RFC
- Any future identity integration would be designed with compatibility in mind

### Alternatives Considered

1. No Action:
   - Continue without formal supply chain security measures
   - Miss opportunities for enterprise adoption
   - Fall behind industry security practices

2. Bespoke Solution:
   - Develop custom SBOM and attestation tooling
   - Risk incompatibility with industry standards
   - Duplicate existing ecosystem solutions
   - Increase maintenance burden

The chosen approach leverages established tools and standards, ensuring compatibility with the broader security ecosystem while minimizing implementation complexity.

### Unresolved Questions

While the implementation path for Phase 1 is clear, using well-established tools and standards (SLSA, in-toto, Sigstore, SPDX), future phases regarding trust architecture and identity integration would require separate RFCs with their own detailed design considerations.

### Conclusion

This RFC proposes a pragmatic approach to enhancing wasmCloud's supply chain security through:
- Immediate implementation of SBOM generation and attestation
- Leveraging industry-standard tools and practices
- Establishing a foundation for future security integration
- Maintaining flexibility for enterprise deployment scenarios

The phased approach allows for immediate security improvements while keeping options open for deeper integration with cloud-native security frameworks.
