### ISSUE TITLE
[BUG] Successfully deployed two applications which both has http server provider listening on same port

### ISSUE THREAD

**Issue by Patrick0308** [wasmCloud/wasmCloud#3845]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Successfully deployed two applications which both has http server provider listening on same port

### Steps to reproduce

1. deploy wasmcloud platform on k8s
2. deploy two http server application
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: HTTP hello world demo in Rust, using the WebAssembly Component Model
      and WebAssembly Interfaces Types (WIT)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1beta1","kind":"Application","metadata":{"annotations":{"description":"HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)","version":"v0.0.1","wasmcloud.dev/authors":"wasmCloud team","wasmcloud.dev/categories":"http,http-server,rust,hello-world,example\n","wasmcloud.dev/homepage":"https://github.com/wasmCloud/wasmCloud/tree/main/examples/rusg/components/http-hello-world","wasmcloud.dev/readme-md-url":"https://github.com/wasmCloud/wasmCloud/blob/main/examples/rusg/components/http-hello-world/README.md","wasmcloud.dev/source-url":"https://github.com/wasmCloud/wasmCloud/blob/main/examples/rusg/components/http-hello-world/wadm.yaml"},"name":"hello-world","namespace":"default"},"spec":{"components":[{"name":"http-component","properties":{"image":"ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0"},"traits":[{"properties":{"replicas":1},"type":"spreadscaler"}],"type":"component"},{"name":"httpserver","properties":{"image":"ghcr.io/wasmcloud/http-server:0.21.0"},"traits":[{"properties":{"interfaces":["incoming-handler"],"namespace":"wasi","package":"http","source_config":[{"name":"default-http","properties":{"address":"127.0.0.1:8080"}}],"target":"http-component"},"type":"link"},{"properties":{"replicas":1},"type":"daemonscaler"}],"type":"capability"}]}}
    version: 01JF97D4V6CSKSBAPGW2B6TAJ7
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/categories: |
      http,http-server,rust,hello-world,example
    wasmcloud.dev/homepage: https://github.com/wasmCloud/wasmCloud/tree/main/examples/rusg/components/http-hello-world
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rusg/components/http-hello-world/README.md
    wasmcloud.dev/source-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/rusg/components/http-hello-world/wadm.yaml
  labels:
    app.kubernetes.io/instance: hello-world
  name: hello-world
  namespace: default
spec:
  components:
  - name: http-component
    properties:
      image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
    traits:
    - properties:
        instances: 1
      type: spreadscaler
    type: component
  - name: httpserver
    properties:
      image: ghcr.io/wasmcloud/http-server:0.23.2
    traits:
    - properties:
        interfaces:
        - incoming-handler
        namespace: wasi
        package: http
        source:
          config:
          - name: default-http
            properties:
              address: 0.0.0.0:8080
        target:
          name: http-component
      type: link
    - properties:
        instances: 1
      type: daemonscaler
    type: capability
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: HTTP hello world demo in Go, using the WebAssembly Component Model
      and WebAssembly Interfaces Types (WIT)
    version: 01JF97D4V6CSKSBAPGW2B6TAJ8
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/categories: |
      http,http-server,golang,hello-world,example
    wasmcloud.dev/homepage: https://github.com/wasmCloud/wasmCloud/tree/main/examples/go/components/http-hello-world
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/go/components/http-hello-world/README.md
    wasmcloud.dev/source-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/go/components/http-hello-world/wadm.yaml
  labels:
    app.kubernetes.io/instance: hello-world-go
  name: hello-world-go
  namespace: default
spec:
  components:
  - name: http-component
    properties:
      image: ghcr.io/wasmcloud/components/http-hello-world-tinygo:0.1.0
    traits:
    - properties:
        instances: 1
      type: spreadscaler
    type: component
  - name: httpserver
    properties:
      image: ghcr.io/wasmcloud/http-server:0.23.2
    traits:
    - properties:
        interfaces:
        - incoming-handler
        namespace: wasi
        package: http
        source:
          config:
          - name: default-http
            properties:
              address: 0.0.0.0:8080
        target:
          name: http-component
      type: link
    - properties:
        instances: 1
      type: daemonscaler
    type: capability

```
3. show application status
```
[patrick:~]$ k get app
APPLICATION      DEPLOYED VERSION             LATEST VERSION               STATUS
hello-world      01JF97D4V6CSKSBAPGW2B6TAJ7   01JF97D4V6CSKSBAPGW2B6TAJ7   Deployed
hello-world-go   01JF97D4V6CSKSBAPGW2B6TAJ8   01JF97D4V6CSKSBAPGW2B6TAJ8   Deployed
```
4. test with curl

![image](https://github.com/user-attachments/assets/2f4cd214-2603-44dd-8aba-b9ff11d9a61e)

### Expected behavior

Deployment  should fail because two applications are listening same port or adding  a feature that two application listening same port based on host routing

### Environment

- OS: MacOS
- Shell zsh
- wasmcloud Version 1.2.1
