### ISSUE TITLE
The service cannot be accessed normally

### ISSUE THREAD

**Issue by dierbei** [wasmCloud/wasmCloud#405]
I just started using wasmCloud.

But I've run into a problem which I'll describe next:

1. First I create a Rust project using wash. The project structure looks like this: 
```shell
~/dierbei/hello# ls
Cargo.lock  Cargo.toml  README.md  build  src  target  wadm.yaml  wasmcloud.toml
```

2. I try to modify the code, according to the documentation example: 
```rust
use wasmbus_rpc::actor::prelude::*;
use wasmcloud_interface_httpserver::{HttpRequest, HttpResponse, HttpServer, HttpServerReceiver};

#[derive(Debug, Default, Actor, HealthResponder)]
#[services(Actor, HttpServer)]
struct HelloActor {}

/// Implementation of the HttpServer capability contract
#[async_trait]
impl HttpServer for HelloActor {
    async fn handle_request(&self, ctx: &Context, req: &HttpRequest) -> RpcResult<HttpResponse> {
        let name = match req.query_string.split("=").collect::<Vec<&str>>()[..] {
            // query string is "name=<name>" e.g. localhost:8080?name=Bob
            ["name", name] => name.to_string(),
            // query string is anything else or empty e.g. localhost:8080
            _ => "World".to_string(),
        };

        Ok(HttpResponse::ok(format!("Hello, {}!", name,)))
    }
}
```

3. I try to modify wadm.yaml file, update version, image, port
```yaml
# This is a full example of how to run the echo actor exposed with an HTTP server. Using this
# example requires you to have WADM running: https://github.com/wasmCloud/wadm/.
#
# To run this example, use: `wash app deploy wadm.yaml`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
  annotations:
    version: v0.0.5
    description: "wasmCloud Hello World Example"
spec:
  components:
    - name: hello
      type: actor
      properties:
        image: /root/dierbei/hello/build/hello_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:7999

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.17.0
        contract: wasmcloud:httpserver
```

4. I tried to redeploy my service by running the following command：
```shell
wash build -o json
wash app undeploy hello
wash app deploy wadm.yaml
curl localhost:7999
```

But I did not access successfully, the following is my request log and service log：
```shell
# curl localhost:7999
curl: (7) Failed to connect to localhost port 7999 after 0 ms: Connection refused
```
```shell
12:37:53.019 [error] actor_ref=/root/dierbei/hello/build/hello_s.wasm span_id=588b57756fefbea2 trace_id=0bd4215154f529543c47ceafb19d91da Failed to start actor /root/dierbei/hello/build/hello_s.wasm, "invalid reference format"
```

![image](https://github.com/wasmCloud/wasmCloud/assets/52097565/fc1baece-0b29-4e84-9c34-6488214a593a)
