### ISSUE TITLE
[FEATURE] Improved error for an invalid wadm.yaml manifest

### ISSUE THREAD

**Issue by mikenikles** [wasmCloud/wasmCloud#4481]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [x] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

When I ran `wash app deploy ./wadm.yaml`, I saw the following error:

```
Unable to parse manifest: Json(Error("expected value", line: 1, column: 1))

Caused by:
    expected value at line 1 column 1
```

It turns out I was missing the `annotations.version` property in my `wadm.yaml` manifest:

```yaml
metadata:
  annotations:
    version: v0.0.1
```

### Describe the solution you'd like

I'd be great to have a more descriptive error 😊

### Describe alternatives you've considered

I compared a working `wadm.yaml` with the one I had and noticed the only difference was the missing `annotations.version` property.

**Comment by mikenikles** [comment]
Following up, I realized https://wasmcloud.com/docs/ecosystem/wadm/model/#application mentions the following:

```yaml
metadata:
  name: hello-world
  annotations:
    description: 'HTTP hello world demo'
    # The version field is optional
    version: v0.0.1
```

Based on my experience, the `version` prop is required, not optioanl.
