### ISSUE TITLE
[BUG] Path-filter action is not properly filtering paths

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#4600]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [x] other / not sure

### Describe the bug

We probably aren't holding it right, but the paths filter isn't properly gating when CI should run:

```
Run dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
  with:
    list-files: shell
    filters: changed:
    - './.github/workflows/wash.yml'
    - './.github/actions/install-cached-wash-cli/action.yml'
    - 'Cargo.lock'
    - 'Cargo.toml'
    - 'crates/control-interface/**'
    - 'crates/core/**'
    - 'crates/secrets-types/**'
    - 'crates/tracing/**'
    - 'crates/wash/**'
    - '!crates/**/*.md'
    - '!crates/wash/.devcontainer'
  
    token: ***
    initial-fetch-depth: 100
  env:
    CARGO_TERM_COLOR: always
    CARGO_INCREMENTAL: 0
    CARGO_PROFILE_TEST_DEBUG: 0
    GO_VERSION: 1.[2](https://github.com/wasmCloud/wasmCloud/actions/runs/15909206431/job/44872007177?pr=4599#step:3:2)4.1
    TINYGO_VERSION: 0.[3](https://github.com/wasmCloud/wasmCloud/actions/runs/15909206431/job/44872007177?pr=4599#step:3:3)6.0
Fetching list of changed files for PR#[4](https://github.com/wasmCloud/wasmCloud/actions/runs/15909206431/job/44872007177?pr=4599#step:3:4)599 from Github API
  Invoking listFiles(pull_number: 4[5](https://github.com/wasmCloud/wasmCloud/actions/runs/15909206431/job/44872007177?pr=4599#step:3:5)99, per_page: 100)
  Received 1 items
  [modified] tests/builtins.rs
Detected 1 changed files
Results:
Filter changed = true
  Matching files:
  tests/builtins.rs [modified]
Changes output set to ["changed"]
```

### Steps to reproduce

See above, I modified tests/builtin.rs which shouldn't match any of the `wash` rules but it does

### Expected behavior

I expect files outside of wash's filters to not trigger wash CI

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]
