### ISSUE TITLE
[BUG] wasmcloud OCI image cannot execute Rust capability providers

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#614]
When running the wasmCloud host with the OCI image, I cannot execute Rust-based capability providers on aarch64-linux.
```
wash start provider wasmcloud.azurecr.io/httpserver:0.19.1

Failed starting provider wasmcloud.azurecr.io/httpserver:0.19.1 on host NCZZ2HCXQNW66BHK3AB6CW3L4W744SHBH3APXLWCJJYLLSJFZEHAGCEU

Caused by:
    failed to spawn provider process: No such file or directory (os error 2)
```

I assume this is due to an exec format error or mismatched GLIBC version, but haven't been able to dig too deep yet.

## To reproduce
Grab this docker compose file
```yaml
version: "4"
services:
  nats:
    image: nats:2.8.4-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: [ "-js" ]
  wasmcloud:
    depends_on:
      - "nats"
    image: wasmcloud/wasmcloud:0.78.0-rc.1
    environment:
      RUST_LOG: trace,async_nats=hyper=info
      WASMCLOUD_LOG_LEVEL: trace
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_PROV_RPC_HOST: nats
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:55681
    ports:
      - "4000:4000"
      - "8080-8089:8080-8089" # Allows exposing examples on ports 8080-8089
```

1. Save it somewhere
2. Run `docker compose -f <file> up`
3. In another terminal window, run `wash start provider wasmcloud.azurecr.io/httpserver:0.19.1`

For additional info, I can start Go capability providers, assuming that's because of a more static binary. `wash start provider ghcr.io/jordan-rash/tsnet-httpserver:v0.2.1`
