### ISSUE TITLE
[FEATURE] support for registry config in wasmcloud.toml

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#860]
**Is your feature request related to a problem? Please describe.**

As a user, I would really like it if I didn't have to manually type out my URL to push my actor every time I need to push a new version.

**Describe the solution you'd like**

I would like for wasmcloud.toml to have a `registry` section that lets you configure the registry you wish to push to. `wash push` can then support reading that file if it exists and pushing.

Additionally, it might be really nice for some way to configure registry credentials that could be stored in the `~/.wash` directory so that I don't have to specify the environment variables every time

**Comment by ahmedtadde** [comment]
so, here's one way to handle this

```toml
# when the `url` arg is specified, the `uri` config field is ignored entirely, only the `credentials` field remains possibly useful.
[registry]
# `WASH_REG_URI` always takes precedence over this field.
uri = "http://localhost:8080"
# `credentials` is an optional field; defaults to `.wash/registry_creds.json`. the file path specified is expected to yield a json object { user, password }
# `WASH_REG_USER` and `WASH_REG_PASSWORD` always take precedence over the values derived from this `credentials` field
# `user` and `password` cmd args always take precedence.
credentials = "./creds.json"
```

of course, the `registry` config entry in `wasmcloud.toml` is itself optional.

let me know if this is adequate.
